/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.gym.pos.view;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import lk.gym.pos.DB.DBConnection;
import lk.gym.pos.view.Details.InstructorDetailsForm;
import lk.gym.pos.view.Details.MemberDetailsForm;
import lk.gym.pos.view.Details.ScheduleDetailsForm;

/**
 *
 * @author DILSHAN
 */
public class DashBord extends javax.swing.JFrame {

    /**
     * Creates new form DashBord
     */
    public DashBord() {
      
            initComponents();
            
          
            
        
    
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        evaluatorCubicCurve2D1 = new org.jdesktop.swing.animation.timing.evaluators.EvaluatorCubicCurve2D();
        jPanel1 = new javax.swing.JPanel();
        close = new javax.swing.JLabel();
        maximize = new javax.swing.JLabel();
        topPanal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        InstructorInfo = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        Schedule = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        ImfoMember = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        logOut = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pay = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        Instructor = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Packages = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        Member = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Attendansy = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        labImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        close.setBackground(new java.awt.Color(255, 255, 255));
        close.setFont(new java.awt.Font("Segoe UI Light", 1, 36)); // NOI18N
        close.setForeground(new java.awt.Color(204, 0, 0));
        close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/gym/pos/Image/delete_32px.png"))); // NOI18N
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });
        jPanel1.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 0, 30, 30));

        maximize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        maximize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/gym/pos/Image/subtract_32px.png"))); // NOI18N
        maximize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                maximizeMouseClicked(evt);
            }
        });
        jPanel1.add(maximize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 0, 30, 30));

        topPanal.setBackground(new java.awt.Color(38, 47, 82,100));
        topPanal.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI Historic", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("RUHUNU FITNESS CENTRE");
        topPanal.add(jLabel1);
        jLabel1.setBounds(249, 49, 488, 48);

        InstructorInfo.setBackground(new java.awt.Color(19, 61, 92));
        InstructorInfo.setPreferredSize(new java.awt.Dimension(160, 160));
        InstructorInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InstructorInfoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                InstructorInfoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                InstructorInfoMouseExited(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Instructor");

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/gym/pos/Image/data.png"))); // NOI18N

        javax.swing.GroupLayout InstructorInfoLayout = new javax.swing.GroupLayout(InstructorInfo);
        InstructorInfo.setLayout(InstructorInfoLayout);
        InstructorInfoLayout.setHorizontalGroup(
            InstructorInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InstructorInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InstructorInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        InstructorInfoLayout.setVerticalGroup(
            InstructorInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InstructorInfoLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        topPanal.add(InstructorInfo);
        InstructorInfo.setBounds(1070, 250, 160, 160);

        Schedule.setBackground(new java.awt.Color(19, 61, 92));
        Schedule.setPreferredSize(new java.awt.Dimension(160, 160));
        Schedule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ScheduleMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ScheduleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ScheduleMouseExited(evt);
            }
        });

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/gym/pos/Image/interface.png"))); // NOI18N

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Schedule");

        javax.swing.GroupLayout ScheduleLayout = new javax.swing.GroupLayout(Schedule);
        Schedule.setLayout(ScheduleLayout);
        ScheduleLayout.setHorizontalGroup(
            ScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ScheduleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ScheduleLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                .addContainerGap())
        );
        ScheduleLayout.setVerticalGroup(
            ScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ScheduleLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        topPanal.add(Schedule);
        Schedule.setBounds(870, 250, 160, 160);

        ImfoMember.setBackground(new java.awt.Color(19, 61, 92));
        ImfoMember.setPreferredSize(new java.awt.Dimension(160, 160));
        ImfoMember.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ImfoMemberMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ImfoMemberMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ImfoMemberMouseExited(evt);
            }
        });

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/gym/pos/Image/tool.png"))); // NOI18N

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Member");

        javax.swing.GroupLayout ImfoMemberLayout = new javax.swing.GroupLayout(ImfoMember);
        ImfoMember.setLayout(ImfoMemberLayout);
        ImfoMemberLayout.setHorizontalGroup(
            ImfoMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ImfoMemberLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ImfoMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                .addContainerGap())
        );
        ImfoMemberLayout.setVerticalGroup(
            ImfoMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ImfoMemberLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        topPanal.add(ImfoMember);
        ImfoMember.setBounds(870, 440, 160, 160);

        jLabel2.setFont(new java.awt.Font("Segoe UI Historic", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("  INFO");
        topPanal.add(jLabel2);
        jLabel2.setBounds(860, 200, 140, 34);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("(Get fit or Get fat)");
        topPanal.add(jLabel3);
        jLabel3.setBounds(680, 100, 126, 20);

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/gym/pos/Image/64X64.png"))); // NOI18N
        topPanal.add(jLabel15);
        jLabel15.setBounds(150, 23, 89, 74);

        logOut.setBackground(new java.awt.Color(19, 61, 92));
        logOut.setPreferredSize(new java.awt.Dimension(160, 160));
        logOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logOutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logOutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logOutMouseExited(evt);
            }
        });

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/gym/pos/Image/logout.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("LogOut");

        javax.swing.GroupLayout logOutLayout = new javax.swing.GroupLayout(logOut);
        logOut.setLayout(logOutLayout);
        logOutLayout.setHorizontalGroup(
            logOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logOutLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(logOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        logOutLayout.setVerticalGroup(
            logOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logOutLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        topPanal.add(logOut);
        logOut.setBounds(150, 440, 160, 160);

        pay.setBackground(new java.awt.Color(19, 61, 92));
        pay.setPreferredSize(new java.awt.Dimension(160, 160));
        pay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                payMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                payMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                payMouseExited(evt);
            }
        });

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/gym/pos/Image/commerce-and-shopping (1).png"))); // NOI18N

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Pay");

        javax.swing.GroupLayout payLayout = new javax.swing.GroupLayout(pay);
        pay.setLayout(payLayout);
        payLayout.setHorizontalGroup(
            payLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(payLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(payLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        payLayout.setVerticalGroup(
            payLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(payLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        topPanal.add(pay);
        pay.setBounds(580, 250, 160, 160);

        Instructor.setBackground(new java.awt.Color(19, 61, 92));
        Instructor.setPreferredSize(new java.awt.Dimension(160, 160));
        Instructor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InstructorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                InstructorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                InstructorMouseExited(evt);
            }
        });

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/gym/pos/Image/card.png"))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Add Instructor");

        javax.swing.GroupLayout InstructorLayout = new javax.swing.GroupLayout(Instructor);
        Instructor.setLayout(InstructorLayout);
        InstructorLayout.setHorizontalGroup(
            InstructorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InstructorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InstructorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                .addContainerGap())
        );
        InstructorLayout.setVerticalGroup(
            InstructorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InstructorLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        topPanal.add(Instructor);
        Instructor.setBounds(360, 250, 160, 160);

        Packages.setBackground(new java.awt.Color(19, 61, 92));
        Packages.setPreferredSize(new java.awt.Dimension(160, 160));
        Packages.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PackagesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PackagesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PackagesMouseExited(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Packages");

        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/gym/pos/Image/pk.png"))); // NOI18N

        javax.swing.GroupLayout PackagesLayout = new javax.swing.GroupLayout(Packages);
        Packages.setLayout(PackagesLayout);
        PackagesLayout.setHorizontalGroup(
            PackagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PackagesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PackagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        PackagesLayout.setVerticalGroup(
            PackagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PackagesLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        topPanal.add(Packages);
        Packages.setBounds(360, 440, 160, 160);

        Member.setBackground(new java.awt.Color(19, 61, 92));
        Member.setPreferredSize(new java.awt.Dimension(160, 160));
        Member.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MemberMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MemberMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MemberMouseExited(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/gym/pos/Image/membercard.png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Add Member");

        javax.swing.GroupLayout MemberLayout = new javax.swing.GroupLayout(Member);
        Member.setLayout(MemberLayout);
        MemberLayout.setHorizontalGroup(
            MemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MemberLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(MemberLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MemberLayout.setVerticalGroup(
            MemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MemberLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        topPanal.add(Member);
        Member.setBounds(150, 250, 160, 160);

        Attendansy.setBackground(new java.awt.Color(19, 61, 92));
        Attendansy.setPreferredSize(new java.awt.Dimension(160, 160));
        Attendansy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AttendansyMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AttendansyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AttendansyMouseExited(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Attendansy");

        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/gym/pos/Image/date.png"))); // NOI18N

        javax.swing.GroupLayout AttendansyLayout = new javax.swing.GroupLayout(Attendansy);
        Attendansy.setLayout(AttendansyLayout);
        AttendansyLayout.setHorizontalGroup(
            AttendansyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AttendansyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AttendansyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        AttendansyLayout.setVerticalGroup(
            AttendansyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AttendansyLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        topPanal.add(Attendansy);
        Attendansy.setBounds(580, 440, 160, 160);

        jPanel1.add(topPanal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        labImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/gym/pos/Image/dashBord.jpg"))); // NOI18N
        jPanel1.add(labImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(1370, 770));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void maximizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maximizeMouseClicked
        // TODO add your handling code here:

     this.setExtendedState(logInForm.ICONIFIED);
    }//GEN-LAST:event_maximizeMouseClicked

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_closeMouseClicked

    private void MemberMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MemberMouseEntered
        // TODO add your handling code here:
        Member.setBackground(new java.awt.Color(28, 135, 219));
    }//GEN-LAST:event_MemberMouseEntered

    private void MemberMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MemberMouseExited
        // TODO add your handling code here:
        Member.setBackground(new java.awt.Color(19, 61, 92));
    }//GEN-LAST:event_MemberMouseExited

    private void InstructorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InstructorMouseEntered
        // TODO add your handling code here:
        Instructor.setBackground(new java.awt.Color(28, 135, 219));
    }//GEN-LAST:event_InstructorMouseEntered

    private void InstructorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InstructorMouseExited
        // TODO add your handling code here:
        Instructor.setBackground(new java.awt.Color(19, 61, 92));
    }//GEN-LAST:event_InstructorMouseExited

    private void payMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_payMouseEntered
        // TODO add your handling code here:
         pay.setBackground(new java.awt.Color(28, 135, 219));
    }//GEN-LAST:event_payMouseEntered

    private void payMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_payMouseExited
        // TODO add your handling code here:
        pay.setBackground(new java.awt.Color(19, 61, 92));
    }//GEN-LAST:event_payMouseExited

    private void InstructorInfoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InstructorInfoMouseEntered
        // TODO add your handling code here:
        InstructorInfo.setBackground(new java.awt.Color(28, 135, 219));
    }//GEN-LAST:event_InstructorInfoMouseEntered

    private void InstructorInfoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InstructorInfoMouseExited
        // TODO add your handling code here:
        InstructorInfo.setBackground(new java.awt.Color(19, 61, 92));
    }//GEN-LAST:event_InstructorInfoMouseExited

    private void ScheduleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ScheduleMouseEntered
        // TODO add your handling code here:
        Schedule.setBackground(new java.awt.Color(28, 135, 219));
    }//GEN-LAST:event_ScheduleMouseEntered

    private void ScheduleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ScheduleMouseExited
        // TODO add your handling code here:
        Schedule.setBackground(new java.awt.Color(19, 61, 92));
    }//GEN-LAST:event_ScheduleMouseExited

    private void ImfoMemberMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImfoMemberMouseEntered
        // TODO add your handling code here:
        ImfoMember.setBackground(new java.awt.Color(28, 135, 219));
    }//GEN-LAST:event_ImfoMemberMouseEntered

    private void ImfoMemberMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImfoMemberMouseExited
        // TODO add your handling code here:
        ImfoMember.setBackground(new java.awt.Color(19, 61, 92));
    }//GEN-LAST:event_ImfoMemberMouseExited

    private void logOutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutMouseEntered
        // TODO add your handling code here:
        logOut.setBackground(new java.awt.Color(28, 135, 219));
    }//GEN-LAST:event_logOutMouseEntered

    private void logOutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutMouseExited
        // TODO add your handling code here:
        logOut.setBackground(new java.awt.Color(19, 61, 92));
    }//GEN-LAST:event_logOutMouseExited

    private void MemberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MemberMouseClicked
        // TODO add your handling code here:
        
        new Member().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_MemberMouseClicked

    private void payMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_payMouseClicked
        // TODO add your handling code here:
       
         new Payments().setVisible(true);
         this.setVisible(false);
    }//GEN-LAST:event_payMouseClicked

    private void InstructorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InstructorMouseClicked
        // TODO add your handling code here:
       
         new Instructor().setVisible(true);
         this.setVisible(false);
    }//GEN-LAST:event_InstructorMouseClicked

    private void logOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new logInForm ().setVisible(true);
    }//GEN-LAST:event_logOutMouseClicked

    private void InstructorInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InstructorInfoMouseClicked
        // TODO add your handling code here:
        
        new InstructorDetailsForm().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_InstructorInfoMouseClicked

    private void PackagesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PackagesMouseEntered
        // TODO add your handling code here:
        Packages.setBackground(new java.awt.Color(28, 135, 219));
    }//GEN-LAST:event_PackagesMouseEntered

    private void PackagesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PackagesMouseExited
        // TODO add your handling code here:
         Packages.setBackground(new java.awt.Color(19, 61, 92));
    }//GEN-LAST:event_PackagesMouseExited

    private void AttendansyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AttendansyMouseEntered
        // TODO add your handling code here:
       Attendansy.setBackground(new java.awt.Color(28, 135, 219));
    }//GEN-LAST:event_AttendansyMouseEntered

    private void AttendansyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AttendansyMouseExited
        // TODO add your handling code here:
        Attendansy.setBackground(new java.awt.Color(19, 61, 92));
    }//GEN-LAST:event_AttendansyMouseExited

    private void ScheduleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ScheduleMouseClicked
        // TODO add your handling code here:
        
        new ScheduleDetailsForm().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ScheduleMouseClicked

    private void ImfoMemberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImfoMemberMouseClicked
        // TODO add your handling code here:
        
        new MemberDetailsForm().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ImfoMemberMouseClicked

    private void PackagesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PackagesMouseClicked
        // TODO add your handling code here:
        new Packages().setVisible(true); 
        this.setVisible(false);
    }//GEN-LAST:event_PackagesMouseClicked

    private void AttendansyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AttendansyMouseClicked
        // TODO add your handling code here:
        
        new Attendance().setVisible(true);
    }//GEN-LAST:event_AttendansyMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashBord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashBord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashBord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashBord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashBord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Attendansy;
    private javax.swing.JPanel ImfoMember;
    private javax.swing.JPanel Instructor;
    private javax.swing.JPanel InstructorInfo;
    private javax.swing.JPanel Member;
    private javax.swing.JPanel Packages;
    private javax.swing.JPanel Schedule;
    private javax.swing.JLabel close;
    private org.jdesktop.swing.animation.timing.evaluators.EvaluatorCubicCurve2D evaluatorCubicCurve2D1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labImage;
    private javax.swing.JPanel logOut;
    private javax.swing.JLabel maximize;
    private javax.swing.JPanel pay;
    private javax.swing.JPanel topPanal;
    // End of variables declaration//GEN-END:variables

    
    
    
      
}
