/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.gym.pos.view;



import java.awt.Image;
import java.io.File;
import java.sql.SQLException;
import java.text.SimpleDateFormat;

import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import lk.gym.pos.Controller.InstructorController;
import lk.gym.pos.Model.InstructorModel;


/**
 *
 * @author DILSHAN
 */
public class Instructor extends javax.swing.JFrame {

    /**
     * Creates new form Instructor
     */
    
    //Gender
    
    
    
    
    public Instructor() {
        initComponents();
        
        //date of join
        Date date=new Date();
        String formatDate=formatDate(date);
        txtDoj.setText(formatDate);
        
        //generate Instructor Id
        generateInstructorId();
        
        //textField Edit
        //clearAllInput();
        
        
    }
    
    //image path and name
       String imageName,imagePath;
        
     private void generateInstructorId() {
        
        
        try {
            String instructorId=new InstructorController().generateId();
            
            labId.setText(instructorId);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Instructor.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }   
       
  
    //date of join----formatDate
    private String formatDate(Date date) {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        return sdf.format(date);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jInternalFrame2 = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        topPanal = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jea = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtContact = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        RadioMale = new javax.swing.JRadioButton();
        RadioFemale = new javax.swing.JRadioButton();
        txtDoj = new javax.swing.JTextField();
        txtDob = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        txtSalary = new javax.swing.JTextField();
        Bsave = new javax.swing.JButton();
        txtAddress = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        labId = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        imageLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labClose = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        topImage = new javax.swing.JLabel();

        jInternalFrame2.setVisible(true);

        javax.swing.GroupLayout jInternalFrame2Layout = new javax.swing.GroupLayout(jInternalFrame2.getContentPane());
        jInternalFrame2.getContentPane().setLayout(jInternalFrame2Layout);
        jInternalFrame2Layout.setHorizontalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame2Layout.setVerticalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        topPanal.setBackground(new java.awt.Color(255, 255, 255,210
        ));
        topPanal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Date Of Join");
        topPanal.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 150, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Instructor Id");
        topPanal.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 140, 40));

        txtName.setBackground(new java.awt.Color(255, 255, 255));
        txtName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtName.setForeground(new java.awt.Color(72, 84, 96));
        txtName.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 1, new java.awt.Color(0, 0, 0)));
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNameKeyPressed(evt);
            }
        });
        topPanal.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 630, 40));

        jea.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jea.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jea.setText("Email Address");
        topPanal.add(jea, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 450, 160, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Contact Number");
        topPanal.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 180, 40));

        txtEmail.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(72, 84, 96));
        txtEmail.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtEmail.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 1, new java.awt.Color(0, 0, 0)));
        topPanal.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(678, 450, 300, 40));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Address");
        topPanal.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, 150, 40));

        txtContact.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtContact.setForeground(new java.awt.Color(72, 84, 96));
        txtContact.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 1, new java.awt.Color(0, 0, 0)));
        topPanal.add(txtContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 450, 190, 40));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Instructor Name");
        topPanal.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 160, 40));

        txtAge.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtAge.setForeground(new java.awt.Color(51, 51, 51));
        txtAge.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAge.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 0, new java.awt.Color(0, 0, 0)));
        txtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeActionPerformed(evt);
            }
        });
        topPanal.add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 200, 71, 40));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Age");
        topPanal.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 200, 90, 40));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Gender");
        topPanal.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 130, 40));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("-Years");
        jLabel11.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 1, new java.awt.Color(0, 0, 0)));
        jLabel11.setOpaque(true);
        topPanal.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 200, 60, 40));

        RadioMale.setBackground(new java.awt.Color(255, 255, 255,210));
        buttonGroup1.add(RadioMale);
        RadioMale.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        RadioMale.setText("Male");
        RadioMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioMaleActionPerformed(evt);
            }
        });
        topPanal.add(RadioMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, 112, -1));

        RadioFemale.setBackground(new java.awt.Color(255, 255, 255,210
        ));
        buttonGroup1.add(RadioFemale);
        RadioFemale.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        RadioFemale.setText("Female");
        RadioFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioFemaleActionPerformed(evt);
            }
        });
        topPanal.add(RadioFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 370, 135, -1));

        txtDoj.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtDoj.setForeground(new java.awt.Color(72, 84, 96));
        txtDoj.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDoj.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        topPanal.add(txtDoj, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 220, 150, 40));

        txtDob.setBackground(new java.awt.Color(255, 255, 255));
        txtDob.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtDob.setForeground(new java.awt.Color(72, 84, 96));
        txtDob.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        topPanal.add(txtDob, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 294, 40));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Salary");
        topPanal.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 620, 120, 40));

        txtSalary.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtSalary.setForeground(new java.awt.Color(72, 84, 96));
        txtSalary.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 1, new java.awt.Color(0, 0, 0)));
        txtSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSalaryActionPerformed(evt);
            }
        });
        topPanal.add(txtSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 620, 180, 40));

        Bsave.setBackground(new java.awt.Color(255, 255, 255));
        Bsave.setFont(new java.awt.Font("Segoe UI Historic", 1, 20)); // NOI18N
        Bsave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/gym/pos/Image/save.png"))); // NOI18N
        Bsave.setText("SAVED");
        Bsave.setBorder(null);
        Bsave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BsaveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BsaveMouseExited(evt);
            }
        });
        Bsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BsaveActionPerformed(evt);
            }
        });
        topPanal.add(Bsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 620, 170, 60));

        txtAddress.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtAddress.setForeground(new java.awt.Color(72, 84, 96));
        txtAddress.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 1, new java.awt.Color(0, 0, 0)));
        topPanal.add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 540, 750, 40));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(11, 232, 129));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/gym/pos/Image/landscape.png"))); // NOI18N
        jLabel13.setText("add image");
        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(11, 232, 129), 3));
        jLabel13.setOpaque(true);
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel13MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel13MouseExited(evt);
            }
        });
        topPanal.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 370, 170, 50));

        labId.setBackground(new java.awt.Color(255, 255, 255));
        labId.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labId.setForeground(new java.awt.Color(72, 84, 96));
        labId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labId.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        labId.setOpaque(true);
        topPanal.add(labId, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 120, 40));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Date Of Birth");
        topPanal.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 150, 40));

        imageLabel.setBackground(new java.awt.Color(236, 239, 241));
        imageLabel.setForeground(new java.awt.Color(170, 166, 157));
        imageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/gym/pos/Image/social.png"))); // NOI18N
        imageLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        imageLabel.setOpaque(true);
        topPanal.add(imageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 60, 250, 290));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText(":");
        topPanal.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 200, 30, 40));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText(":");
        topPanal.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 30, 40));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText(":");
        topPanal.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 30, 40));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText(":");
        topPanal.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 30, 40));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText(":");
        topPanal.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 30, 40));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText(":");
        topPanal.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 450, 30, 40));

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(72, 84, 96));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("RS : ");
        jLabel21.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 0, new java.awt.Color(0, 0, 0)));
        jLabel21.setOpaque(true);
        topPanal.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 620, 60, 40));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText(":");
        topPanal.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 450, 30, 40));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText(":");
        topPanal.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 540, 30, 40));

        jLabel24.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(72, 84, 96));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("+94 -");
        jLabel24.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 0, new java.awt.Color(0, 0, 0)));
        jLabel24.setOpaque(true);
        topPanal.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 450, 50, 40));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        topPanal.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 670, 220, 20));

        jLabel25.setBackground(new java.awt.Color(255, 255, 255));
        jLabel25.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 0, new java.awt.Color(0, 0, 0)));
        jLabel25.setOpaque(true);
        topPanal.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 540, 30, 40));

        jLabel26.setBackground(new java.awt.Color(255, 255, 255));
        jLabel26.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 0, new java.awt.Color(0, 0, 0)));
        jLabel26.setOpaque(true);
        topPanal.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 30, 40));

        jLabel27.setBackground(new java.awt.Color(255, 255, 255));
        jLabel27.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 0, new java.awt.Color(0, 0, 0)));
        jLabel27.setOpaque(true);
        topPanal.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 450, 20, 40));

        jPanel1.add(topPanal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1370, 710));

        jPanel3.setBackground(new java.awt.Color(11, 232, 129));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("INSTRUCTOR");

        labClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/gym/pos/Image/delete_32px.png"))); // NOI18N
        labClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labCloseMouseExited(evt);
            }
        });

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/gym/pos/Image/subtract_32px.png"))); // NOI18N
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/gym/pos/Image/left_32px.png"))); // NOI18N
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 305, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(297, 297, 297)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labClose)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labClose)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addGap(0, 28, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 60));

        topImage.setBackground(new java.awt.Color(255, 255, 255));
        topImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        topImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/gym/pos/Image/540X542.png"))); // NOI18N
        topImage.setOpaque(true);
        jPanel1.add(topImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1370, 710));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1370, 770));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void RadioMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioMaleActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_RadioMaleActionPerformed

    private void RadioFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioFemaleActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_RadioFemaleActionPerformed

    private void txtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeActionPerformed

    private void txtSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSalaryActionPerformed
     
    
    
  
    private void BsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BsaveActionPerformed
        
        try {
            // TODO add your handling code here:
            
         String   id=labId.getText();
         String   name=txtName.getText();
         String  doj=txtDoj.getText();
            
         SimpleDateFormat df=new SimpleDateFormat("YYYY-MM-dd");
         String   dob=df.format(txtDob.getDate());
          
         String gender;
         if(RadioMale.isSelected()){
                gender="Male";
            }else if (RadioFemale.isSelected()){
                gender="Female";
                
            }else{
                gender="Other";
            }
          
          String  email=txtEmail.getText();
          int  contact=Integer.parseInt(txtContact.getText());
          String  address=txtAddress.getText();
          int  age=Integer.parseInt(txtAge.getText());
          String  salary=txtSalary.getText();
            
          
            InstructorModel x=new InstructorModel(id,name,doj,dob,gender,email,contact,address,age,salary,imageName,imagePath);
            
            if(new InstructorController().saveInstructor(x)){
                JOptionPane.showMessageDialog(this,"INSTRUCTOR SAVED..");
                clearAllInput();
                generateInstructorId();
            }else{  
                JOptionPane.showMessageDialog(this,"TRY AGAIN...");
                clearAllInput();
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Instructor.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_BsaveActionPerformed

    private void BsaveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BsaveMouseEntered
        // TODO add your handling code here:
        Bsave.setBackground(new java.awt.Color(51,255,102));
    }//GEN-LAST:event_BsaveMouseEntered

    private void BsaveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BsaveMouseExited
        // TODO add your handling code here:
         Bsave.setBackground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_BsaveMouseExited

    private void labCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labCloseMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_labCloseMouseClicked

    private void labCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labCloseMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_labCloseMouseEntered

    private void labCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labCloseMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_labCloseMouseExited

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        // TODO add your handling code here:
        this.setExtendedState(Payments.ICONIFIED);
    }//GEN-LAST:event_jLabel18MouseClicked

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        // TODO add your handling code here:
        DashBord dash=new DashBord();dash.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel19MouseClicked

    private void txtNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtNameKeyPressed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtNameActionPerformed

        
    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
        //default image Location
        String currentDisplayPath="C:\\Users\\DILSHAN\\Desktop\\sample Image";
        JFileChooser imageFileChooser=new JFileChooser(currentDisplayPath);
        int imageChooser=imageFileChooser.showOpenDialog(null);
        imageFileChooser.setDialogTitle("Choose Image....");
        
        //only choose "png","jpg","jpeng" fils
        FileNameExtensionFilter fexf= new FileNameExtensionFilter("IMAGE","png","jpg","jpeg");
        imageFileChooser.setFileFilter(fexf);
        
        
        if(imageChooser==JFileChooser.APPROVE_OPTION){
            File imageFile=imageFileChooser.getSelectedFile();
            String imageFileName=imageFile.getName();
            String imageFilePath=imageFile.getAbsolutePath();
            //display image path and name view
                imageName=imageFileName;
                imagePath=imageFilePath;
            ImageIcon imageIcon=new ImageIcon(imageFilePath);
            //Resize image file to jlabel
            Image image=imageIcon.getImage().getScaledInstance(imageLabel.getWidth(),imageLabel.getHeight(),Image.SCALE_SMOOTH);
            
            ImageIcon resizeImageIcon=new ImageIcon(image);
            imageLabel.setIcon(resizeImageIcon);
           
        }
        
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseEntered
        // TODO add your handling code here:
        //jLabel1.setBackground(new java.awt.Color(255, 242, 0));
    }//GEN-LAST:event_jLabel13MouseEntered

    private void jLabel13MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseExited
        // TODO add your handling code here:
       // jLabel1.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_jLabel13MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Instructor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Instructor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Instructor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Instructor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Instructor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bsave;
    private javax.swing.JRadioButton RadioFemale;
    private javax.swing.JRadioButton RadioMale;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel jea;
    private javax.swing.JLabel labClose;
    private javax.swing.JLabel labId;
    private javax.swing.JLabel topImage;
    private javax.swing.JPanel topPanal;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtContact;
    private com.toedter.calendar.JDateChooser txtDob;
    private javax.swing.JTextField txtDoj;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSalary;
    // End of variables declaration//GEN-END:variables

     ///clear method
    private void clearAllInput(){
        
        txtAge.setText(null);
        txtName.setText(null);
        txtContact.setText(null);
        buttonGroup1.clearSelection();
        txtAddress.setText(null);
        txtEmail.setText(null);
        txtSalary.setText(null);
       imageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/gym/pos/Image/social.png"))); // NOI18N

        
    }
  
}
