/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.gym.pos.view;

import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lk.gym.pos.Controller.MemberController;
import lk.gym.pos.Controller.PackageController;
import lk.gym.pos.Controller.PaymentController;
import lk.gym.pos.Model.MemberModel;
import lk.gym.pos.Model.PackageModel;
import lk.gym.pos.Model.PaymentModel;

/**
 *
 * @author DILSHAN
 */
public class Payments extends javax.swing.JFrame {

    /**
     * Creates new form Packages
     */
    public Payments() {
        initComponents();
        
        //Generate paymentId
        generatePaymentId();
        
        //All package Name
        loadAllPackageName();
        
        //load All memberid
        loadAllMemberId();
        
        //date
        Date date=new Date();
        String formatDate=formatDate(date);
        labDate.setText(formatDate);
        
        //tableload
        detailsRefrish();
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        labDuration = new javax.swing.JLabel();
        labId = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Bcalculate = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtDiscount = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        paymentId = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtAccount = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        labBalanse = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        labTotalAmount = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        cmbMethod = new rojerusan.RSComboMetro();
        txtCash = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        labt = new javax.swing.JLabel();
        Bpay = new javax.swing.JButton();
        labDate = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labDiscountAmount = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        cmbpid = new rojerusan.RSComboMetro();
        jLabel33 = new javax.swing.JLabel();
        cmbMid = new rojerusan.RSComboMetro();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        txtName = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        todayPaymentTable = new javax.swing.JTable();
        jLabel28 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        searchbar = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labClose = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel1MouseEntered(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labDuration.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labDuration.setForeground(new java.awt.Color(72, 84, 96));
        labDuration.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labDuration.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(labDuration, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 200, 200, 40));

        labId.setBackground(new java.awt.Color(204, 204, 204));
        labId.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labId.setForeground(new java.awt.Color(255, 153, 51));
        labId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labId.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(labId, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 130, 200, 40));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Package price");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 150, 40));

        txtAmount.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtAmount.setForeground(new java.awt.Color(72, 84, 96));
        txtAmount.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtAmount.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 1, new java.awt.Color(0, 0, 0)));
        txtAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAmountActionPerformed(evt);
            }
        });
        jPanel1.add(txtAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 190, 40));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Discount");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 120, 40));

        Bcalculate.setBackground(new java.awt.Color(255, 255, 255));
        Bcalculate.setFont(new java.awt.Font("Segoe UI Historic", 1, 20)); // NOI18N
        Bcalculate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/gym/pos/Image/calculator.png"))); // NOI18N
        Bcalculate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BcalculateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BcalculateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BcalculateMouseExited(evt);
            }
        });
        jPanel1.add(Bcalculate, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, 50, 50));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Segoe UI Historic", 1, 40)); // NOI18N
        jLabel11.setText("%");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 40, 40));

        txtDiscount.setFont(new java.awt.Font("Segoe UI", 3, 20)); // NOI18N
        txtDiscount.setForeground(new java.awt.Color(0, 153, 0));
        txtDiscount.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDiscount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtDiscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiscountActionPerformed(evt);
            }
        });
        jPanel1.add(txtDiscount, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 100, 40));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Package Id");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, 140, 40));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("DATE");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 130, 40));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(null);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Balanse");
        jPanel5.add(jLabel14);
        jLabel14.setBounds(40, 230, 130, 40);

        paymentId.setBackground(new java.awt.Color(255, 255, 255));
        paymentId.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        paymentId.setForeground(new java.awt.Color(255, 102, 0));
        paymentId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        paymentId.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        paymentId.setOpaque(true);
        jPanel5.add(paymentId);
        paymentId.setBounds(210, 0, 170, 40);

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Payment Id");
        jPanel5.add(jLabel20);
        jLabel20.setBounds(30, 0, 120, 40);

        txtAccount.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtAccount.setForeground(new java.awt.Color(127, 127, 127));
        txtAccount.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 1, new java.awt.Color(0, 0, 0)));
        txtAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAccountActionPerformed(evt);
            }
        });
        jPanel5.add(txtAccount);
        txtAccount.setBounds(230, 110, 250, 40);

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Method");
        jPanel5.add(jLabel21);
        jLabel21.setBounds(30, 50, 130, 40);

        labBalanse.setBackground(new java.awt.Color(255, 255, 255));
        labBalanse.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labBalanse.setForeground(new java.awt.Color(102, 102, 102));
        labBalanse.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 1, new java.awt.Color(0, 0, 0)));
        labBalanse.setOpaque(true);
        jPanel5.add(labBalanse);
        labBalanse.setBounds(250, 230, 230, 40);

        jPanel3.setBackground(new java.awt.Color(127, 127, 127));
        jPanel3.setLayout(null);

        jLabel16.setFont(new java.awt.Font("Segoe UI Light", 3, 20)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 153, 0));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("PACKAGE DETAILS..");
        jPanel3.add(jLabel16);
        jLabel16.setBounds(10, 10, 200, 50);

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText(" SALE AMOUNT");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(400, 410, 170, 40);

        labTotalAmount.setFont(new java.awt.Font("Segoe UI Light", 3, 20)); // NOI18N
        labTotalAmount.setForeground(new java.awt.Color(255, 153, 51));
        labTotalAmount.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(labTotalAmount);
        labTotalAmount.setBounds(610, 410, 170, 40);

        jLabel9.setFont(new java.awt.Font("Segoe UI Light", 1, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("DISCOUNT");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(430, 290, 120, 40);

        jLabel18.setFont(new java.awt.Font("Segoe UI Light", 1, 20)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText(" METHOD");
        jPanel3.add(jLabel18);
        jLabel18.setBounds(680, 0, 160, 40);

        jPanel5.add(jPanel3);
        jPanel3.setBounds(-690, 170, 460, 380);

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Account No");
        jPanel5.add(jLabel24);
        jLabel24.setBounds(40, 110, 120, 40);

        cmbMethod.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "BANK TRANSFER", "CASH TRANSFER" }));
        cmbMethod.setColorArrow(new java.awt.Color(44, 62, 80));
        cmbMethod.setColorBorde(new java.awt.Color(44, 62, 80));
        cmbMethod.setColorFondo(new java.awt.Color(44, 62, 80));
        cmbMethod.setFont(new java.awt.Font("Segoe UI Light", 3, 18)); // NOI18N
        cmbMethod.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbMethodItemStateChanged(evt);
            }
        });
        jPanel5.add(cmbMethod);
        cmbMethod.setBounds(210, 50, 230, 40);

        txtCash.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtCash.setForeground(new java.awt.Color(127, 127, 127));
        txtCash.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 1, new java.awt.Color(0, 0, 0)));
        txtCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCashActionPerformed(evt);
            }
        });
        jPanel5.add(txtCash);
        txtCash.setBounds(250, 170, 230, 40);

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Cash");
        jPanel5.add(jLabel26);
        jLabel26.setBounds(40, 170, 120, 40);

        jLabel31.setBackground(new java.awt.Color(255, 255, 255));
        jLabel31.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 0, new java.awt.Color(0, 0, 0)));
        jLabel31.setOpaque(true);
        jPanel5.add(jLabel31);
        jLabel31.setBounds(210, 110, 20, 40);

        jLabel36.setBackground(new java.awt.Color(255, 255, 255));
        jLabel36.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(72, 84, 96));
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setText("RS : ");
        jLabel36.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 0, new java.awt.Color(0, 0, 0)));
        jLabel36.setOpaque(true);
        jPanel5.add(jLabel36);
        jLabel36.setBounds(210, 230, 50, 40);

        jLabel41.setBackground(new java.awt.Color(255, 255, 255));
        jLabel41.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(72, 84, 96));
        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel41.setText("RS : ");
        jLabel41.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 0, new java.awt.Color(0, 0, 0)));
        jLabel41.setOpaque(true);
        jPanel5.add(jLabel41);
        jLabel41.setBounds(210, 170, 50, 40);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("TOTAL AMOUNT");
        jPanel5.add(jLabel4);
        jLabel4.setBounds(0, 310, 190, 40);

        labt.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labt.setForeground(new java.awt.Color(102, 255, 102));
        labt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.add(labt);
        labt.setBounds(220, 300, 260, 50);

        Bpay.setBackground(new java.awt.Color(255, 255, 255));
        Bpay.setFont(new java.awt.Font("Segoe UI Historic", 1, 20)); // NOI18N
        Bpay.setForeground(new java.awt.Color(63, 202, 137));
        Bpay.setText("PAY");
        Bpay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        Bpay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BpayMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BpayMouseExited(evt);
            }
        });
        Bpay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BpayActionPerformed(evt);
            }
        });
        jPanel5.add(Bpay);
        Bpay.setBounds(270, 360, 210, 60);

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 70, 490, 440));

        labDate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labDate.setForeground(new java.awt.Color(72, 84, 96));
        labDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labDate.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(labDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, 210, 40));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/gym/pos/Image/brands-and-logotypes.png"))); // NOI18N
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 350, 130, 90));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Member Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 160, 40));

        labDiscountAmount.setFont(new java.awt.Font("Segoe UI Light", 3, 20)); // NOI18N
        labDiscountAmount.setForeground(new java.awt.Color(255, 153, 51));
        labDiscountAmount.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labDiscountAmount.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 1, new java.awt.Color(0, 0, 0)));
        jPanel1.add(labDiscountAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 270, 150, 40));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Duratiom");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, 130, 40));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/gym/pos/Image/brands-and-logotypes (1).png"))); // NOI18N
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 350, 140, 80));

        cmbpid.setColorArrow(new java.awt.Color(44, 62, 80));
        cmbpid.setColorBorde(java.awt.Color.lightGray);
        cmbpid.setColorFondo(new java.awt.Color(44, 62, 80));
        cmbpid.setFont(new java.awt.Font("Segoe UI Light", 3, 18)); // NOI18N
        cmbpid.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbpidItemStateChanged(evt);
            }
        });
        jPanel1.add(cmbpid, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 230, 40));

        jLabel33.setBackground(new java.awt.Color(255, 255, 255));
        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("Package Name");
        jPanel1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 150, 40));

        cmbMid.setColorArrow(new java.awt.Color(44, 62, 80));
        cmbMid.setColorBorde(java.awt.Color.lightGray);
        cmbMid.setColorFondo(new java.awt.Color(44, 62, 80));
        cmbMid.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        cmbMid.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbMidItemStateChanged(evt);
            }
        });
        jPanel1.add(cmbMid, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 230, 40));

        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("Amount");
        jPanel1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 270, 130, 40));

        jLabel35.setBackground(new java.awt.Color(255, 255, 255));
        jLabel35.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setText("Member Id");
        jPanel1.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 170, 40));

        txtName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtName.setForeground(new java.awt.Color(72, 84, 96));
        txtName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtName.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 1, new java.awt.Color(0, 0, 0)));
        txtName.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 590, 40));

        jLabel39.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 30, 40));

        jLabel38.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(72, 84, 96));
        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel38.setText("RS : ");
        jLabel38.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 50, 40));

        jLabel40.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(72, 84, 96));
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel40.setText("RS : ");
        jLabel40.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 270, 50, 40));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator2.setAlignmentX(4.0F);
        jSeparator2.setAlignmentY(0.4F);
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(852, 60, 10, 360));

        jLabel13.setFont(new java.awt.Font("Sylfaen", 3, 20)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("PAYEMENT DETAILS..");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 10, 230, 50));

        todayPaymentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "PAYMENT ID", "MEMBER ID", "MEMBER NAME", "PACKAGE ID", "PACKAGE NAME", "DISCOUNT %", "DISCOUNT RS.", "DATE", "PAYMENT METHOD", "ACCOUNT NO", "CASH", "BALANSE", "TOTAL AMOUNT"
            }
        ));
        todayPaymentTable.setRowHeight(25);
        jScrollPane1.setViewportView(todayPaymentTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 1350, 190));

        jLabel28.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, 10, 40));

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/gym/pos/Image/search_40px.png"))); // NOI18N
        jLabel22.setOpaque(true);
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 50, 40));

        searchbar.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        searchbar.setForeground(new java.awt.Color(72, 84, 96));
        searchbar.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        searchbar.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        searchbar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchbarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searchbarMouseExited(evt);
            }
        });
        searchbar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbarActionPerformed(evt);
            }
        });
        searchbar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchbarKeyReleased(evt);
            }
        });
        jPanel1.add(searchbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, 430, 40));

        jPanel4.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1370, 710));

        jPanel2.setBackground(new java.awt.Color(11, 232, 129));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PAYMENTS");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/gym/pos/Image/left_32px.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        labClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/gym/pos/Image/delete_32px.png"))); // NOI18N
        labClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labCloseMouseExited(evt);
            }
        });

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/gym/pos/Image/subtract_32px.png"))); // NOI18N
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(412, 412, 412)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 437, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labClose)
                .addGap(22, 22, 22))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(labClose)
                    .addComponent(jLabel12))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1370, 770));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
        
    Double forCalculation;
    private void BcalculateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BcalculateMouseEntered
        // TODO add your handling code here:
        
        Bcalculate.setBackground(new java.awt.Color(255,102,102));
    }//GEN-LAST:event_BcalculateMouseEntered

    private void BcalculateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BcalculateMouseExited
        // TODO add your handling code here:
        Bcalculate.setBackground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_BcalculateMouseExited

    private void BcalculateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BcalculateMouseClicked
        // TODO add your handling code here:
     
        //DSICOUNT CALCULATION
     Double presantage =Double.parseDouble(txtDiscount.getText());
     Double DA=forCalculation*presantage/100;
     labDiscountAmount.setText(DA+"");
     
        //TOTALAMOUNT CALCULATION
        double total=forCalculation-DA;
        labTotalAmount.setText(total+"");
    }//GEN-LAST:event_BcalculateMouseClicked

    private void jPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MouseEntered

    private void BpayMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BpayMouseEntered
        // TODO add your handling code here:
        Bpay.setBackground(new java.awt.Color(63, 202, 137));
        Bpay.setForeground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_BpayMouseEntered

    private void BpayMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BpayMouseExited
        // TODO add your handling code here:
        Bpay.setBackground(new java.awt.Color(255,255,255));
        Bpay.setForeground(new java.awt.Color(63,202,137));
    }//GEN-LAST:event_BpayMouseExited

    private void txtDiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiscountActionPerformed
        // TODO add your handling code here:
        
        //DSICOUNT CALCULATION
     Double presantage =Double.parseDouble(txtDiscount.getText());
     Double DA=forCalculation*presantage/100;
     labDiscountAmount.setText("  "+DA);
     
        //TOTALAMOUNT CALCULATION
        double total=forCalculation-DA;
        labTotalAmount.setText("  "+total);
    }//GEN-LAST:event_txtDiscountActionPerformed

    private void labCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labCloseMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_labCloseMouseClicked

    private void labCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labCloseMouseEntered
        // TODO add your handling code here:
       
    }//GEN-LAST:event_labCloseMouseEntered

    private void labCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labCloseMouseExited
        // TODO add your handling code here:
        
    }//GEN-LAST:event_labCloseMouseExited

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        this.setExtendedState(Payments.ICONIFIED);
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
       DashBord dash=new DashBord();dash.setVisible(true);
      this.setVisible(false);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void txtAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAccountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAccountActionPerformed

    private void txtCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCashActionPerformed
        // TODO add your handling code here:
        Double packagePrice=Double.parseDouble(txtAmount.getText());
        Double discountAmount=Double.parseDouble(labDiscountAmount.getText());
        
        Double totalAmount=packagePrice-discountAmount;
        labt.setText(totalAmount+"");
        
        Double cash=Double.parseDouble(txtCash.getText());
        Double balanse=cash-totalAmount;
        labBalanse.setText(balanse+"");
    }//GEN-LAST:event_txtCashActionPerformed

    private void cmbMethodItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbMethodItemStateChanged
        // TODO add your handling code here:
        
        
       
        int m=cmbMethod.getSelectedIndex();
        if(m!=0){
            txtAccount.setText("Null");
        }else{
            //JOptionPane.showMessageDialog(this,"hdcgsd");
            txtAccount.setText(null);
        }
        
    }//GEN-LAST:event_cmbMethodItemStateChanged

    private void cmbpidItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbpidItemStateChanged
       
        try {
           
            String packages=cmbpid.getSelectedItem().toString();
            PackageModel pk=new PackageController().searchPackageName(packages);
            labId.setText(pk.getPackage_id());
            labDuration.setText(pk.getDuration());
            txtAmount.setText(pk.getAmount().toString());
            forCalculation=pk.getAmount();
            
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Payments.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmbpidItemStateChanged

    private void cmbMidItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbMidItemStateChanged
        try {
            // TODO add your handling code here:
            String memberId=cmbMid.getSelectedItem().toString();
            MemberModel m=new MemberController().getMemberName(memberId);
            
            txtName.setText(m.getName());
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Payments.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmbMidItemStateChanged

    private void BpayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BpayActionPerformed
        try {
            // TODO add your handling code here:
            String payment_id=paymentId.getText();
            
            
            String member_id=cmbMid.getSelectedItem().toString();
           
            String member_name=txtName.getText();
            String package_id=labId.getText();
            String package_name=cmbpid.getSelectedItem().toString();
            Double  discount_prasantage=Double.parseDouble(txtDiscount.getText());
            Double discount_amount=Double.parseDouble(labDiscountAmount.getText());
            
           
            String date=labDate.getText();
            String payment_method=cmbMethod.getSelectedItem().toString();
            
            String account_number=txtAccount.getText();
            Double cash=Double.parseDouble(txtCash.getText());
            Double balance=Double.parseDouble(labBalanse.getText());
            Double total_amount=Double.parseDouble(labt.getText());
            
            PaymentModel p=new PaymentModel(payment_id,member_id,member_name,package_id,package_name,discount_prasantage,discount_amount,date,payment_method,
                    account_number,cash,balance,total_amount);
            
            
            if(new PaymentController().savePaymentDetails(p)){
                JOptionPane.showMessageDialog(this,"payed");
                detailsRefrish();
                
            }else{ 
                JOptionPane.showMessageDialog(this,"tryagain");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Payments.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }//GEN-LAST:event_BpayActionPerformed

    private void txtAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAmountActionPerformed

    private void searchbarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchbarMouseEntered
        // TODO add your handling code here:
        searchbar.setText(null);
    }//GEN-LAST:event_searchbarMouseEntered

    private void searchbarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchbarMouseExited
        // TODO add your handling code here:
        searchbar.setText("Search...");
    }//GEN-LAST:event_searchbarMouseExited

    private void searchbarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchbarActionPerformed

    private void searchbarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchbarKeyReleased
       
        try {
            DefaultTableModel model=(DefaultTableModel) todayPaymentTable.getModel();
            // TODO add your handling code here:
            model.setRowCount(0);
            List<PaymentModel> allPayment = new PaymentController().searchAllPayment(searchbar.getText());
            for(PaymentModel temp : allPayment){
                model.addRow(new Object[]{
                    temp.getPayment_id(),
                    temp.getMember_id(),
                    temp.getMember_name(),
                    temp.getPackage_id(),
                    temp.getPackage_name(),
                    temp.getDiscount_prasantage(),
                    temp.getDiscount_amount(),
                    temp.getDate(),
                    temp.getPayment_method(),
                    temp.getAccount_number(),
                    temp.getCash(),
                    temp.getBalance(),
                    temp.getTotal_amount(),
                    
                    
                });
                
            }
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(Payments.class.getName()).log(Level.SEVERE, null, ex);
        }
            
            


    }//GEN-LAST:event_searchbarKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payments().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bcalculate;
    private javax.swing.JButton Bpay;
    private rojerusan.RSComboMetro cmbMethod;
    private rojerusan.RSComboMetro cmbMid;
    private rojerusan.RSComboMetro cmbpid;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel labBalanse;
    private javax.swing.JLabel labClose;
    private javax.swing.JLabel labDate;
    private javax.swing.JLabel labDiscountAmount;
    private javax.swing.JLabel labDuration;
    private javax.swing.JLabel labId;
    private javax.swing.JLabel labTotalAmount;
    private javax.swing.JLabel labt;
    private javax.swing.JLabel paymentId;
    private javax.swing.JTextField searchbar;
    private javax.swing.JTable todayPaymentTable;
    private javax.swing.JTextField txtAccount;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtCash;
    private javax.swing.JTextField txtDiscount;
    private javax.swing.JLabel txtName;
    // End of variables declaration//GEN-END:variables

    private void loadAllPackageName() {
       
        try {
            ArrayList<PackageModel> packages=new PackageController().allPackageName();
            
            for(PackageModel pk :packages){
                cmbpid.addItem(pk.getPackage_name());
                
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Payments.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    private void generatePaymentId() {
        
        try {
            String id=new PaymentController().generatePaymentId();
            paymentId.setText(id);
            
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(Payments.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loadAllMemberId() {
        try {
            ArrayList<MemberModel> Member=new MemberController().allMemberId();
            
            for(MemberModel Mem :Member){
                cmbMid.addItem(Mem.getmId());
                
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Payments.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private String formatDate(Date date) {
       
       SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        return sdf.format(date);
    }
   
    private void detailsRefrish() {
        try {
            ArrayList<PaymentModel> todayPayment = PaymentController.getTodayPayment();
            DefaultTableModel  model=(DefaultTableModel) todayPaymentTable.getModel();
            model.setRowCount(0);
            for (PaymentModel pay : todayPayment) {
                
                Object[] rowData={pay.getPayment_id(),pay.getMember_id(),pay.getMember_name(),pay.getPackage_id(),pay.getPackage_name(),pay.getDiscount_prasantage(),pay.getDiscount_amount(),
                    pay.getDate(),pay.getPayment_method(),pay.getAccount_number(),pay.getCash(),pay.getBalance(),pay.getTotal_amount()
                };
                model.addRow(rowData);
            }
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(Payments.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void cmbClear(){
       //cmbMid .setSelectedIndex(-1);
       cmbpid.setSelectedIndex(-1);
    }
}
