/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.gym.pos.view.Details;

import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.io.File;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import lk.gym.pos.Controller.InstructorController;
import lk.gym.pos.Model.InstructorModel;
import lk.gym.pos.view.DashBord;

/**
 *
 * @author DILSHAN
 */
public class InstructorDetailsForm extends javax.swing.JFrame {

    /**
     * Creates new form InstructorDetailsForm
     */
    public InstructorDetailsForm() {
        initComponents();
        detailsRefrish();
        //tableCustamization();
       
       SearchBar.setText("Search...");
       
       tableCustamization();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labClose = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        SearchBar = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtContact = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtSalary = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtGender = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtDob = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        txtDoj = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        UPDATE = new javax.swing.JLabel();
        DELETE = new javax.swing.JLabel();
        clear = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        labImage = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(11, 232, 129));

        jLabel1.setFont(new java.awt.Font("Segoe UI Historic", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("INSTRUCTOR DETAILS");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/gym/pos/Image/left_32px.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        labClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/gym/pos/Image/delete_32px.png"))); // NOI18N
        labClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labCloseMouseExited(evt);
            }
        });

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/gym/pos/Image/subtract_32px.png"))); // NOI18N
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 407, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(332, 332, 332)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labClose)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(labClose)
                    .addComponent(jLabel12))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, -1));

        table.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NAME", "ADDRESS", "CONTACT NO", "EMAIL", "GENDER", "DATE OF BIRTH", "ADE", "DATE OF JOIN", "SALARY", "IMAGE NAME", "IMAGE PATH"
            }
        ));
        table.setFocusable(false);
        table.setGridColor(new java.awt.Color(153, 153, 153));
        table.setIntercellSpacing(new java.awt.Dimension(0, 0));
        table.setRowHeight(25);
        table.setSelectionBackground(new java.awt.Color(128, 142, 155));
        table.setShowVerticalLines(false);
        table.getTableHeader().setReorderingAllowed(false);
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 1370, 250));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Rs :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, 50, 30));

        txtAddress.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtAddress.setForeground(new java.awt.Color(72, 84, 96));
        txtAddress.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtAddress.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 1, new java.awt.Color(0, 0, 0)));
        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });
        jPanel1.add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 630, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Instructor Id :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 140, 30));

        txtId.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        txtId.setForeground(new java.awt.Color(11, 232, 129));
        txtId.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtId.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        jPanel1.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 100, 50));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Instructor Name :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 180, 30));

        txtEmail.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(72, 84, 96));
        txtEmail.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 1, new java.awt.Color(0, 0, 0)));
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 220, 300, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText(" Personal Address :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 190, 30));

        txtName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtName.setForeground(new java.awt.Color(72, 84, 96));
        txtName.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtName.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 1, new java.awt.Color(0, 0, 0)));
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, 350, 40));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Age");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 140, 30));

        SearchBar.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        SearchBar.setForeground(new java.awt.Color(72, 84, 96));
        SearchBar.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        SearchBar.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        SearchBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SearchBarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SearchBarMouseExited(evt);
            }
        });
        SearchBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBarActionPerformed(evt);
            }
        });
        SearchBar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SearchBarKeyReleased(evt);
            }
        });
        jPanel1.add(SearchBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 470, 390, 40));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Salary");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 90, 30));

        txtContact.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtContact.setForeground(new java.awt.Color(72, 84, 96));
        txtContact.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtContact.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 1, new java.awt.Color(0, 0, 0)));
        txtContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContactActionPerformed(evt);
            }
        });
        jPanel1.add(txtContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 210, 40));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText(" Contact Number :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 190, 30));

        txtSalary.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtSalary.setForeground(new java.awt.Color(72, 84, 96));
        txtSalary.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtSalary.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 1, new java.awt.Color(0, 0, 0)));
        txtSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSalaryActionPerformed(evt);
            }
        });
        jPanel1.add(txtSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, 250, 40));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText(" Gender");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 150, 30));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText(":");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 30, 30));

        txtGender.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtGender.setForeground(new java.awt.Color(72, 84, 96));
        txtGender.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtGender.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 1, new java.awt.Color(0, 0, 0)));
        txtGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGenderActionPerformed(evt);
            }
        });
        jPanel1.add(txtGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 130, 40));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText(" Date Of Birth :");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, 150, 30));

        txtDob.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtDob.setForeground(new java.awt.Color(72, 84, 96));
        txtDob.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtDob.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 1, new java.awt.Color(0, 0, 0)));
        txtDob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDobActionPerformed(evt);
            }
        });
        jPanel1.add(txtDob, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 280, 300, 40));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText(" Date Of Join :");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 350, 160, 30));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText(":");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 30, 30));

        txtAge.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtAge.setForeground(new java.awt.Color(72, 84, 96));
        txtAge.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtAge.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 1, new java.awt.Color(0, 0, 0)));
        txtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeActionPerformed(evt);
            }
        });
        jPanel1.add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, 140, 40));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setAlignmentX(2.0F);
        jSeparator1.setAlignmentY(2.0F);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(862, 80, -1, 400));

        txtDoj.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtDoj.setForeground(new java.awt.Color(72, 84, 96));
        txtDoj.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtDoj.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 1, new java.awt.Color(0, 0, 0)));
        txtDoj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDojActionPerformed(evt);
            }
        });
        jPanel1.add(txtDoj, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 340, 300, 40));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText(" Email :");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, 70, 30));

        UPDATE.setBackground(new java.awt.Color(255, 255, 255));
        UPDATE.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        UPDATE.setForeground(new java.awt.Color(6, 82, 221));
        UPDATE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UPDATE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/gym/pos/Image/square.png"))); // NOI18N
        UPDATE.setText("UPDATE");
        UPDATE.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(6, 82, 221), 2));
        UPDATE.setOpaque(true);
        UPDATE.setPreferredSize(new java.awt.Dimension(53, 31));
        UPDATE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UPDATEMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                UPDATEMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                UPDATEMouseExited(evt);
            }
        });
        jPanel1.add(UPDATE, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 170, 140, 50));

        DELETE.setBackground(new java.awt.Color(255, 255, 255));
        DELETE.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        DELETE.setForeground(new java.awt.Color(255, 77, 77));
        DELETE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DELETE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/gym/pos/Image/button.png"))); // NOI18N
        DELETE.setText("DELETE");
        DELETE.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 77, 77), 2));
        DELETE.setOpaque(true);
        DELETE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DELETEMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DELETEMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DELETEMouseExited(evt);
            }
        });
        jPanel1.add(DELETE, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 290, 140, 50));

        clear.setBackground(new java.awt.Color(255, 255, 255));
        clear.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        clear.setForeground(new java.awt.Color(11, 232, 129));
        clear.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clear.setText("CLEAR");
        clear.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(11, 232, 129), 2));
        clear.setOpaque(true);
        clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clearMouseExited(evt);
            }
        });
        jPanel1.add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 420, 140, 50));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("PHOTO");
        jLabel10.setOpaque(true);
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 440, 110, 50));

        labImage.setBackground(new java.awt.Color(236, 239, 241));
        labImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/gym/pos/Image/social.png"))); // NOI18N
        labImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        labImage.setOpaque(true);
        jPanel1.add(labImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 120, 250, 300));

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/gym/pos/Image/search_40px.png"))); // NOI18N
        jLabel18.setOpaque(true);
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 470, 50, 40));

        jLabel19.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 470, 10, 40));

        jLabel20.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, 20, 40));

        jLabel21.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 20, 40));

        jLabel22.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 20, 40));

        jLabel23.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 20, 40));

        jLabel24.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 20, 40));

        jLabel25.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 220, 20, 40));

        jLabel26.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 340, 20, 40));

        jLabel27.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 280, 20, 40));

        jLabel28.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, 20, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1370, 770));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        DashBord dash=new DashBord();dash.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void labCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labCloseMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_labCloseMouseClicked

    private void labCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labCloseMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_labCloseMouseEntered

    private void labCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labCloseMouseExited
        // TODO add your handling code here:

    }//GEN-LAST:event_labCloseMouseExited

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        this.setExtendedState(InstructorDetailsForm.ICONIFIED);
    }//GEN-LAST:event_jLabel12MouseClicked

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void SearchBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBarActionPerformed
        // TODO add your handling code here:
    
    }//GEN-LAST:event_SearchBarActionPerformed

    private void txtContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContactActionPerformed

    private void txtSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSalaryActionPerformed

    private void txtGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGenderActionPerformed

    private void txtDobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDobActionPerformed

    private void txtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeActionPerformed

    private void txtDojActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDojActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDojActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        Clear();
       DefaultTableModel model=(DefaultTableModel) table.getModel();
        int tsbleSelectedRow=table.getSelectedRow();
       txtId.setText(model.getValueAt(tsbleSelectedRow, 0).toString());
       txtName.setText(model.getValueAt(tsbleSelectedRow, 1).toString());
       txtAddress.setText(model.getValueAt(tsbleSelectedRow, 2).toString()); 
       txtContact.setText(model.getValueAt(tsbleSelectedRow, 3).toString()); 
       txtEmail.setText(model.getValueAt(tsbleSelectedRow, 4).toString()); 
       txtGender.setText(model.getValueAt(tsbleSelectedRow, 5).toString()); 
       txtDob.setText(model.getValueAt(tsbleSelectedRow, 6).toString()); 
       txtAge.setText(model.getValueAt(tsbleSelectedRow, 7).toString()); 
       txtDoj.setText(model.getValueAt(tsbleSelectedRow, 8).toString());
       txtSalary.setText(model.getValueAt(tsbleSelectedRow, 9).toString());
      
        
        String imagePath= model.getValueAt(tsbleSelectedRow, 11).toString();
       
        ImageIcon imageIcon=new ImageIcon(imagePath);
        Image image=imageIcon.getImage().getScaledInstance(labImage.getWidth(),labImage.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon resizeImageIcon=new ImageIcon(image);
        labImage.setIcon(resizeImageIcon);
       
      
    }//GEN-LAST:event_tableMouseClicked
            String imageName,imagePath;
           
    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
      
        String currentDisplayPath="C:\\Users\\DILSHAN\\Desktop\\sample Image";
        JFileChooser imageFileChooser=new JFileChooser(currentDisplayPath);
        int imageChooser=imageFileChooser.showOpenDialog(null);
        imageFileChooser.setDialogTitle("Choose Image....");
        
        //only choose "png","jpg","jpeng" fils
        FileNameExtensionFilter fexf= new FileNameExtensionFilter("IMAGE","png","jpg","jpeg");
        imageFileChooser.setFileFilter(fexf);
        
        
        if(imageChooser==JFileChooser.APPROVE_OPTION){
            File imageFile=imageFileChooser.getSelectedFile();
            String imageFileName=imageFile.getName();
            String imageFilePath=imageFile.getAbsolutePath();
            //display image path and name view
                imageName=imageFileName;
                imagePath=imageFilePath;
            ImageIcon imageIcon=new ImageIcon(imageFilePath);
            //Resize image file to jlabel
            Image image=imageIcon.getImage().getScaledInstance(labImage.getWidth(),labImage.getHeight(),Image.SCALE_SMOOTH);
            
            ImageIcon resizeImageIcon=new ImageIcon(image);
            labImage.setIcon(resizeImageIcon);
           
        }
        
    }//GEN-LAST:event_jLabel10MouseClicked

    private void UPDATEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UPDATEMouseClicked
        try {
            // TODO add your handling code here:
            String   id=txtId.getText();
            String   name=txtName.getText();
            String  doj=txtDoj.getText();
            
            
            String   dob=txtDob.getText();
            
            String gender=txtGender.getText();
            
            String  email=txtEmail.getText();
           
            int  contact=Integer.parseInt(txtContact.getText());
            String  address=txtAddress.getText();
            int  age=Integer.parseInt(txtAge.getText());
            String  salary=txtSalary.getText();
            
           
            if(id.isEmpty() || name.isEmpty() || doj.isEmpty() || gender.isEmpty() || email.isEmpty() ||  address.isEmpty() ||  salary.isEmpty() ){
                JOptionPane.showMessageDialog(this,"Empty text....");
               
            }else{
            
            InstructorModel x=new InstructorModel(id,name,doj,dob,gender,email,contact,address,age,salary,imageName,imagePath);
            if(new InstructorController().updateInstructor(x)){
                JOptionPane.showMessageDialog(this,"INSTRUCTOR UPDATED..");
                  System.out.println(imagePath);
                detailsRefrish();
            }else{  
                JOptionPane.showMessageDialog(this,"TRY AGAIN...");
                detailsRefrish();
            }
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(InstructorDetailsForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_UPDATEMouseClicked

    private void DELETEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DELETEMouseClicked
        try {
            // TODO add your handling code here:
            String id=txtId.getText();
            
           
            if(new InstructorController().deleteInstructor(id)){
                JOptionPane.showMessageDialog(this,"Deleted");
                detailsRefrish();
            }else{
                JOptionPane.showMessageDialog(this,"try again");
                detailsRefrish();
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(InstructorDetailsForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_DELETEMouseClicked

    private void clearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMouseClicked
        // TODO add your handling code here:
        detailsRefrish();
        
    }//GEN-LAST:event_clearMouseClicked

    private void UPDATEMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UPDATEMouseEntered
        // TODO add your handling code here:
        UPDATE.setForeground(new java.awt.Color(255, 255, 255));
       UPDATE.setBackground(new java.awt.Color(6, 82, 221));
    }//GEN-LAST:event_UPDATEMouseEntered

    private void UPDATEMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UPDATEMouseExited
        // TODO add your handling code here:
        UPDATE.setForeground(new java.awt.Color(6, 82, 221));
        UPDATE.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_UPDATEMouseExited

    private void DELETEMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DELETEMouseEntered
        // TODO add your handling code here:
       DELETE.setForeground(new java.awt.Color(255, 255, 255));
       DELETE.setBackground(new java.awt.Color(255, 77, 77));
    }//GEN-LAST:event_DELETEMouseEntered

    private void DELETEMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DELETEMouseExited
        // TODO add your handling code here:
        DELETE.setForeground(new java.awt.Color(255, 77, 77));
        DELETE.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_DELETEMouseExited

    private void clearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMouseEntered
        // TODO add your handling code here:
        clear.setForeground(new java.awt.Color(255, 255, 255));
      clear.setBackground(new java.awt.Color(11, 232, 129));
    }//GEN-LAST:event_clearMouseEntered

    private void clearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMouseExited
        // TODO add your handling code here:
       clear.setForeground(new java.awt.Color(11, 232, 129));
        clear.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_clearMouseExited

    private void SearchBarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SearchBarKeyReleased
        try {
            // TODO add your handling code here:
            dtm.setRowCount(0);
            List<InstructorModel> allDetails = new InstructorController().searchAllInstructor(SearchBar.getText());
            for(InstructorModel temp: allDetails){
                dtm.addRow(new Object[]{
                    temp.getId(),
                    temp.getName(),
                    temp.getDoj(),
                    temp.getDob(),
                    temp.getGender(),
                    temp.getEmail(),
                    temp.getContact(),
                    temp.getAddress(),
                    temp.getAge(),
                    temp.getSalary(),
                    temp.getImageName(),
                    temp.getImagePath(),
                     
                    
                });
                
                
                
               
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(InstructorDetailsForm.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }//GEN-LAST:event_SearchBarKeyReleased

    private void SearchBarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchBarMouseEntered
        // TODO add your handling code here:
        SearchBar.setText(null);
    }//GEN-LAST:event_SearchBarMouseEntered

    private void SearchBarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchBarMouseExited
        // TODO add your handling code here:
        SearchBar.setText("Search...");
    }//GEN-LAST:event_SearchBarMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InstructorDetailsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InstructorDetailsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InstructorDetailsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InstructorDetailsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InstructorDetailsForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DELETE;
    private javax.swing.JTextField SearchBar;
    private javax.swing.JLabel UPDATE;
    private javax.swing.JLabel clear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labClose;
    private javax.swing.JLabel labImage;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtContact;
    private javax.swing.JTextField txtDob;
    private javax.swing.JTextField txtDoj;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSalary;
    // End of variables declaration//GEN-END:variables
    DefaultTableModel dtm;
    private void detailsRefrish() {
        Clear();
        try {
            ArrayList<InstructorModel> allInstructor = InstructorController.getAllInstructor();
            dtm=(DefaultTableModel) table.getModel();
            dtm.setRowCount(0);
            for (InstructorModel instructor : allInstructor) {
                
                Object[] rowData={instructor.getId(),instructor.getName(),instructor.getAddress(),instructor.getContact(),instructor.getEmail(),
                    instructor.getGender(),instructor.getDob(),instructor.getAge(),instructor.getDoj(),instructor.getSalary(),instructor.getImageName(),instructor.getImagePath()};
                
                dtm.addRow(rowData);

            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(InstructorDetailsForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void Clear(){
        txtId.setText(null);
        txtName.setText(null);
        txtAddress.setText(null);
        txtEmail.setText(null);
        txtSalary.setText(null);
        txtDob.setText(null);
        txtAge.setText(null);
        txtContact.setText(null);
        txtDoj.setText(null);
        txtGender.setText( null);
       
        labImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/gym/pos/Image/social.png"))); // NOI18N
        
    }
    
    private void tableCustamization(){
       table.getTableHeader().setFont(new Font("Segoe UI",Font.BOLD,15));
       table.getTableHeader().setOpaque(false);
       table.getTableHeader().setBackground(new Color(255, 255, 255));
       table.getTableHeader().setForeground(new Color(30, 39, 46));
      
    }
}
