/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package lk.gym.pos.view.Details;

import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.io.File;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import lk.gym.pos.Controller.MemberController;
import lk.gym.pos.Model.MemberModel;
import lk.gym.pos.view.DashBord;
import lk.gym.pos.view.Payments;

/**
 *
 * @author DILSHAN
 */
public class MemberDetailsForm extends javax.swing.JFrame {

    /** Creates new form MemberDetailsForm */
    public MemberDetailsForm() {
        initComponents();
        detailsRefrish();
         
         searchbar.setText("Search...");
         
         
         //table
         tableCustamization();
      
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        labClose = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        labImage = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtContact = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txtDob = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtGender = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        searchbar = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtDoj = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        txtHeight = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        txtWeight = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        UPDATE = new javax.swing.JLabel();
        DELETE = new javax.swing.JLabel();
        Clear_and_Refrish = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(11, 227, 126));

        labClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/gym/pos/Image/delete_32px.png"))); // NOI18N
        labClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labCloseMouseExited(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MEMBERSHIP DETAILS");

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/gym/pos/Image/subtract_32px.png"))); // NOI18N
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/gym/pos/Image/left_32px.png"))); // NOI18N
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 316, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(286, 286, 286)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labClose)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labClose)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 60));

        labImage.setBackground(new java.awt.Color(236, 239, 241));
        labImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/gym/pos/Image/social.png"))); // NOI18N
        labImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        labImage.setOpaque(true);
        jPanel1.add(labImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 140, 250, 300));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Member Id :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 140, 30));

        txtId.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        txtId.setForeground(new java.awt.Color(11, 232, 129));
        txtId.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtId.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        jPanel1.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 100, 50));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Member Name :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 180, 30));

        txtName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtName.setForeground(new java.awt.Color(72, 84, 96));
        txtName.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtName.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 1, new java.awt.Color(0, 0, 0)));
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, 350, 40));

        txtAddress.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtAddress.setForeground(new java.awt.Color(72, 84, 96));
        txtAddress.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtAddress.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 1, new java.awt.Color(0, 0, 0)));
        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });
        jPanel1.add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 630, 40));

        jLabel20.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, 20, 40));

        jLabel21.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 20, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText(" Member Address :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 190, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText(" Contact Number :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 180, 30));

        txtContact.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtContact.setForeground(new java.awt.Color(72, 84, 96));
        txtContact.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtContact.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 1, new java.awt.Color(0, 0, 0)));
        txtContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContactActionPerformed(evt);
            }
        });
        jPanel1.add(txtContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 210, 40));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText(" Email :");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, 70, 30));

        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(72, 84, 96));
        txtEmail.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 1, new java.awt.Color(0, 0, 0)));
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 220, 300, 40));

        jLabel25.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 220, 20, 40));

        txtDob.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtDob.setForeground(new java.awt.Color(72, 84, 96));
        txtDob.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtDob.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 1, new java.awt.Color(0, 0, 0)));
        txtDob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDobActionPerformed(evt);
            }
        });
        jPanel1.add(txtDob, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 280, 300, 40));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText(" Date Of Birth :");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, 150, 30));

        txtGender.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtGender.setForeground(new java.awt.Color(72, 84, 96));
        txtGender.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtGender.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 1, new java.awt.Color(0, 0, 0)));
        txtGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGenderActionPerformed(evt);
            }
        });
        jPanel1.add(txtGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 130, 40));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText(" Gender");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 150, 30));

        jLabel24.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 20, 40));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Weight");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 420, 100, 30));

        searchbar.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        searchbar.setForeground(new java.awt.Color(72, 84, 96));
        searchbar.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        searchbar.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        searchbar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchbarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searchbarMouseExited(evt);
            }
        });
        searchbar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbarActionPerformed(evt);
            }
        });
        searchbar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchbarKeyReleased(evt);
            }
        });
        jPanel1.add(searchbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 480, 430, 40));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText(":");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, 30, 40));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText(":");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 30, 40));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText(" Date Of Join :");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 350, 160, 30));

        txtDoj.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtDoj.setForeground(new java.awt.Color(72, 84, 96));
        txtDoj.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtDoj.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 1, new java.awt.Color(0, 0, 0)));
        txtDoj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDojActionPerformed(evt);
            }
        });
        jPanel1.add(txtDoj, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 340, 300, 40));

        jLabel26.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 340, 20, 40));

        jLabel27.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 280, 20, 40));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setAlignmentX(2.0F);
        jSeparator1.setAlignmentY(2.0F);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(864, 80, 0, 380));

        jLabel36.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 20, 40));

        jLabel37.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 20, 40));

        txtAge.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtAge.setForeground(new java.awt.Color(72, 84, 96));
        txtAge.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtAge.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 1, new java.awt.Color(0, 0, 0)));
        txtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeActionPerformed(evt);
            }
        });
        jPanel1.add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, 140, 40));

        jLabel38.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel38.setText("Ft");
        jPanel1.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, 30, 40));

        txtHeight.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtHeight.setForeground(new java.awt.Color(72, 84, 96));
        txtHeight.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtHeight.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 1, new java.awt.Color(0, 0, 0)));
        txtHeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHeightActionPerformed(evt);
            }
        });
        jPanel1.add(txtHeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, 90, 40));

        jLabel39.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, 30, 40));

        jLabel40.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel40.setText(":");
        jPanel1.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 30, 40));

        jLabel42.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel42.setText(":");
        jPanel1.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 410, 30, 40));

        jLabel41.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel41.setText("Age");
        jPanel1.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 140, 30));

        jLabel43.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel43.setText("Height");
        jPanel1.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 140, 30));

        jLabel44.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 410, 30, 40));

        jLabel45.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel45.setText("Kg");
        jPanel1.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 410, 30, 40));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "MEMBER ID", "MEMBER NAME", "ADDRESS", "CONTACT NO", "EMAIL", "GENDER", "DATE OF JOIN", "DATE OF BIRTH", "AGE", "HEIGHT", "WEIGHT", "IMAGENAME", "IMAGEPATH"
            }
        ));
        table.setRowHeight(25);
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tableMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 1370, 230));

        txtWeight.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtWeight.setForeground(new java.awt.Color(72, 84, 96));
        txtWeight.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtWeight.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 1, new java.awt.Color(0, 0, 0)));
        txtWeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWeightActionPerformed(evt);
            }
        });
        jPanel1.add(txtWeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 410, 80, 40));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 90, 10, 360));

        UPDATE.setBackground(new java.awt.Color(255, 255, 255));
        UPDATE.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        UPDATE.setForeground(new java.awt.Color(6, 82, 221));
        UPDATE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UPDATE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/gym/pos/Image/square.png"))); // NOI18N
        UPDATE.setText("UPDATE");
        UPDATE.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(6, 82, 221), 2));
        UPDATE.setOpaque(true);
        UPDATE.setPreferredSize(new java.awt.Dimension(53, 31));
        UPDATE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UPDATEMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                UPDATEMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                UPDATEMouseExited(evt);
            }
        });
        jPanel1.add(UPDATE, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 170, 140, 50));

        DELETE.setBackground(new java.awt.Color(255, 255, 255));
        DELETE.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        DELETE.setForeground(new java.awt.Color(255, 77, 77));
        DELETE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DELETE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/gym/pos/Image/button.png"))); // NOI18N
        DELETE.setText("DELETE");
        DELETE.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 77, 77), 2));
        DELETE.setOpaque(true);
        DELETE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DELETEMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DELETEMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DELETEMouseExited(evt);
            }
        });
        jPanel1.add(DELETE, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 290, 140, 50));

        Clear_and_Refrish.setBackground(new java.awt.Color(255, 255, 255));
        Clear_and_Refrish.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        Clear_and_Refrish.setForeground(new java.awt.Color(11, 232, 129));
        Clear_and_Refrish.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Clear_and_Refrish.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/gym/pos/Image/erase.png"))); // NOI18N
        Clear_and_Refrish.setText("CLEAR");
        Clear_and_Refrish.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(11, 232, 129), 2));
        Clear_and_Refrish.setOpaque(true);
        Clear_and_Refrish.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Clear_and_RefrishMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Clear_and_RefrishMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Clear_and_RefrishMouseExited(evt);
            }
        });
        jPanel1.add(Clear_and_Refrish, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 420, 140, 50));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("PHOTO");
        jLabel10.setOpaque(true);
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 460, 110, 50));

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/gym/pos/Image/search_40px.png"))); // NOI18N
        jLabel22.setOpaque(true);
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 480, 50, 40));

        jLabel23.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 480, 10, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(0, 0, 1370, 770);
    }// </editor-fold>//GEN-END:initComponents
        String ImageName,ImagePath;
    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        // TODO add your handling code here:
        DashBord dash=new DashBord();dash.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel19MouseClicked

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        // TODO add your handling code here:
        this.setExtendedState(Payments.ICONIFIED);
    }//GEN-LAST:event_jLabel18MouseClicked

    private void labCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labCloseMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_labCloseMouseExited

    private void labCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labCloseMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_labCloseMouseEntered

    private void labCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labCloseMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_labCloseMouseClicked

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed

    private void txtContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContactActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtDobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDobActionPerformed

    private void txtGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGenderActionPerformed

    private void searchbarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchbarActionPerformed

    private void txtDojActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDojActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDojActionPerformed

    private void txtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeActionPerformed

    private void txtHeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHeightActionPerformed

    private void txtWeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWeightActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel) table.getModel();
        int tsbleSelectedRow=table.getSelectedRow();
       txtId.setText(model.getValueAt(tsbleSelectedRow, 0).toString());
       txtName.setText(model.getValueAt(tsbleSelectedRow, 1).toString());
       txtAddress.setText(model.getValueAt(tsbleSelectedRow, 2).toString()); 
       txtContact.setText(model.getValueAt(tsbleSelectedRow, 3).toString()); 
       txtEmail.setText(model.getValueAt(tsbleSelectedRow, 4).toString()); 
       txtGender.setText(model.getValueAt(tsbleSelectedRow, 5).toString()); 
       txtDob.setText(model.getValueAt(tsbleSelectedRow, 7).toString()); 
       txtDoj.setText(model.getValueAt(tsbleSelectedRow, 6).toString());
     
       txtAge.setText(model.getValueAt(tsbleSelectedRow, 8).toString()); 
        txtHeight.setText(model.getValueAt(tsbleSelectedRow, 9).toString());
        txtWeight.setText(model.getValueAt(tsbleSelectedRow, 10).toString());
       
        
        String imagePath= model.getValueAt(tsbleSelectedRow, 12).toString();
       
        ImageIcon imageIcon=new ImageIcon(imagePath);
        Image image=imageIcon.getImage().getScaledInstance(labImage.getWidth(),labImage.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon resizeImageIcon=new ImageIcon(image);
        labImage.setIcon(resizeImageIcon);
    }//GEN-LAST:event_tableMouseClicked

    private void tableMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tableMouseReleased

    private void searchbarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchbarKeyReleased
        try {
            // TODO add your handling code here:
            model.setRowCount(0);
            List<MemberModel> allDetails = new MemberController().searchAllMember(searchbar.getText());
            for(MemberModel temp: allDetails){
                model.addRow(new Object[]{
                    temp.getmId(),
                    temp.getName(),
                    temp.getDoj(),
                    temp.getDob(),
                    temp.getGender(),
                    temp.getEmail(),
                    temp.getContact(),
                    temp.getAddress(),
                    temp.getAge(),
                    temp.getHeight(),
                    temp.getWeight(),
                    temp.getImageName(),
                    temp.getImagePath(),
                    // public InstructorModel(String id, String name, String doj, String dob, String gender, String email, int contact, 
                    //String address, int age, String salary,String imageName,String imagePath ) {
                    
                });
               
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MemberDetailsForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MemberDetailsForm.class.getName()).log(Level.SEVERE, null, ex);
        }
                
    }//GEN-LAST:event_searchbarKeyReleased

    private void UPDATEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UPDATEMouseClicked
            
        
        try {
            String mId=txtId.getText();
            String name=txtName.getText();
            String doj=txtDoj.getText();
            String dob=txtDob.getText();
            String age=txtAge.getText();
            Double height=Double.parseDouble(txtHeight.getText());
            Double weight=Double.parseDouble(txtWeight.getText());
            String gender=txtGender.getText();
            String contact=txtContact.getText();
            String address=txtAddress.getText();
            String email=txtEmail.getText();
            
            
            MemberModel m=new MemberModel(mId,name,address,contact,email,gender,doj,dob,age,height,weight,ImageName,ImagePath);
            
            if(new MemberController().updateMemberDetails(m)){
                JOptionPane.showMessageDialog(this,"saved");
                detailsRefrish();
            }else{
                JOptionPane.showMessageDialog(this,"Tryagain");
            }
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(MemberDetailsForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_UPDATEMouseClicked

    private void UPDATEMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UPDATEMouseEntered
        // TODO add your handling code here:
        UPDATE.setForeground(new java.awt.Color(255, 255, 255));
        UPDATE.setBackground(new java.awt.Color(6, 82, 221));
    }//GEN-LAST:event_UPDATEMouseEntered

    private void UPDATEMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UPDATEMouseExited
        // TODO add your handling code here:
        UPDATE.setForeground(new java.awt.Color(6, 82, 221));
        UPDATE.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_UPDATEMouseExited

    private void DELETEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DELETEMouseClicked
        try {
            // TODO add your handling code here:
            String id=txtId.getText();

            if(new MemberController().deleteMember(id)){
                JOptionPane.showMessageDialog(this,"Deleted");
                detailsRefrish();
            }else{
                JOptionPane.showMessageDialog(this,"try again");
                detailsRefrish();
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(InstructorDetailsForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_DELETEMouseClicked

    private void DELETEMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DELETEMouseEntered
        // TODO add your handling code here:
        DELETE.setForeground(new java.awt.Color(255, 255, 255));
        DELETE.setBackground(new java.awt.Color(255, 77, 77));
    }//GEN-LAST:event_DELETEMouseEntered

    private void DELETEMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DELETEMouseExited
        // TODO add your handling code here:
        DELETE.setForeground(new java.awt.Color(255, 77, 77));
        DELETE.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_DELETEMouseExited

    private void Clear_and_RefrishMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Clear_and_RefrishMouseClicked
        // TODO add your handling code here:
        detailsRefrish();

    }//GEN-LAST:event_Clear_and_RefrishMouseClicked

    private void Clear_and_RefrishMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Clear_and_RefrishMouseEntered
        // TODO add your handling code here:
        Clear_and_Refrish.setForeground(new java.awt.Color(255, 255, 255));
        Clear_and_Refrish.setBackground(new java.awt.Color(11, 232, 129));
    }//GEN-LAST:event_Clear_and_RefrishMouseEntered

    private void Clear_and_RefrishMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Clear_and_RefrishMouseExited
        // TODO add your handling code here:
        Clear_and_Refrish.setForeground(new java.awt.Color(11, 232, 129));
        Clear_and_Refrish.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_Clear_and_RefrishMouseExited

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:

        String currentDisplayPath="C:\\Users\\DILSHAN\\Desktop\\sample Image";
        JFileChooser imageFileChooser=new JFileChooser(currentDisplayPath);
        int imageChooser=imageFileChooser.showOpenDialog(null);
        imageFileChooser.setDialogTitle("Choose Image....");

        //only choose "png","jpg","jpeng" fils
        FileNameExtensionFilter fexf= new FileNameExtensionFilter("IMAGE","png","jpg","jpeg");
        imageFileChooser.setFileFilter(fexf);

        if(imageChooser==JFileChooser.APPROVE_OPTION){
            File imageFile=imageFileChooser.getSelectedFile();
            String imageFileName=imageFile.getName();
            String imageFilePath=imageFile.getAbsolutePath();
            //display image path and name view
            ImageName=imageFileName;
            ImagePath=imageFilePath;
            ImageIcon imageIcon=new ImageIcon(imageFilePath);
            //Resize image file to jlabel
            Image image=imageIcon.getImage().getScaledInstance(labImage.getWidth(),labImage.getHeight(),Image.SCALE_SMOOTH);

            ImageIcon resizeImageIcon=new ImageIcon(image);
            labImage.setIcon(resizeImageIcon);

        }
    }//GEN-LAST:event_jLabel10MouseClicked

    private void searchbarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchbarMouseEntered
        // TODO add your handling code here:
        searchbar.setText(null);
    }//GEN-LAST:event_searchbarMouseEntered

    private void searchbarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchbarMouseExited
        // TODO add your handling code here:
         searchbar.setText("Search...");
    }//GEN-LAST:event_searchbarMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MemberDetailsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MemberDetailsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MemberDetailsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MemberDetailsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MemberDetailsForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Clear_and_Refrish;
    private javax.swing.JLabel DELETE;
    private javax.swing.JLabel UPDATE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel labClose;
    private javax.swing.JLabel labImage;
    private javax.swing.JTextField searchbar;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtContact;
    private javax.swing.JTextField txtDob;
    private javax.swing.JTextField txtDoj;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextField txtHeight;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtWeight;
    // End of variables declaration//GEN-END:variables
     DefaultTableModel model;
    private void detailsRefrish() {
        Clear();
        try {
            ArrayList<MemberModel> allMembers = MemberController.getAllMember();
            model=(DefaultTableModel) table.getModel();
            model.setRowCount(0);
            for (MemberModel Member : allMembers) {
                
                Object[] rowData={Member.getmId(),Member.getName(),Member.getAddress(),Member.getContact(),Member.getEmail(),
                    Member.getGender(),Member.getDoj(),Member.getDob(),Member.getAge(),Member.getHeight(),Member.getWeight(),Member.getImageName(),Member.getImagePath()};
                
                model.addRow(rowData);
            }   } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(MemberDetailsForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void Clear() {
       txtId.setText(null);
       txtName.setText(null);
       txtAddress.setText(null);
       txtContact.setText(null);
       txtEmail.setText(null);
       txtGender.setText(null);
       txtDob.setText(null);
       txtDoj.setText(null);
       txtAge.setText(null);
       txtHeight.setText(null);
       txtWeight.setText(null);
       labImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/gym/pos/Image/social.png"))); // NOI18N

    }
    private void tableCustamization(){
       table.getTableHeader().setFont(new Font("Segoe UI",Font.BOLD,15));
       //table.getTableHeader().setOpaque(false);
      // table.getTableHeader().setBackground(new Color(255, 255, 255));
       //table.getTableHeader().setForeground(new Color(30, 39, 46));
       //table. setBackground(new Color(0,0,0,0));
    }
}
