/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.gym.pos.view.Details;

import java.awt.Color;
import java.awt.Font;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import lk.gym.pos.Controller.InstructorController;
import lk.gym.pos.Controller.MemberController;
import lk.gym.pos.Controller.ScheduleController;
import lk.gym.pos.Model.InstructorModel;
import lk.gym.pos.Model.MemberModel;
import lk.gym.pos.Model.ScheduleDetailsModel;
import lk.gym.pos.Model.ScheduleModel;
import lk.gym.pos.view.DashBord;

/**
 *
 * @author DILSHAN
 */
public class ScheduleDetailsForm extends javax.swing.JFrame {

    /**
     * Creates new form ScheduleDetailsForm
     */
    public ScheduleDetailsForm() {
        initComponents();
        

        //load All memberid
        loadAllMemberId();

        //load All Instructor
        loadAllInstroctorId();

        //date of join
        Date date = new Date();
        String formatDate = formatDate(date);
        labDate.setText(formatDate);

        ////ScheduleId
        generateScheduleId();
        
        //scheduletableLoad
        detailsRefrish();
        txtNo.setText("1");
        searchbar.setText("Search...");
        
        
      tableCustamization();

    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        labClose = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        labId = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        labDate = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        labMemberName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        labFequency = new javax.swing.JTextField();
        ADD = new javax.swing.JLabel();
        txtExercise = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableSchedule = new javax.swing.JTable();
        cmbMid = new rojerusan.RSComboMetro();
        cmbInstructorId = new rojerusan.RSComboMetro();
        jLabel11 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        labInstructorName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableScheduleDetails = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txtNo = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        searchbar = new javax.swing.JTextField();
        DELETE = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(64, 64, 122));

        labClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/gym/pos/Image/delete_32px.png"))); // NOI18N
        labClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labCloseMouseExited(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SCHEDULE DETAILS");

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/gym/pos/Image/subtract_32px.png"))); // NOI18N
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/gym/pos/Image/left_32px.png"))); // NOI18N
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 316, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(286, 286, 286)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labClose)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labClose)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 60));

        labId.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        labId.setForeground(new java.awt.Color(11, 232, 129));
        labId.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        labId.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        labId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                labIdActionPerformed(evt);
            }
        });
        jPanel1.add(labId, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 100, 50));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Date");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 120, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Schedule Id");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 140, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Frequency ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 150, -1, 30));

        labDate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labDate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(labDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, 260, 40));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Member Id");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 140, 30));

        jLabel38.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 20, 40));

        labMemberName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labMemberName.setForeground(new java.awt.Color(72, 84, 96));
        labMemberName.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        labMemberName.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 1, new java.awt.Color(0, 0, 0)));
        labMemberName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                labMemberNameActionPerformed(evt);
            }
        });
        jPanel1.add(labMemberName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 600, 40));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Instructor Id");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 140, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Exercise");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 70, 80, 30));

        labFequency.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labFequency.setForeground(new java.awt.Color(72, 84, 96));
        labFequency.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        labFequency.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        labFequency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                labFequencyActionPerformed(evt);
            }
        });
        labFequency.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                labFequencyKeyReleased(evt);
            }
        });
        jPanel1.add(labFequency, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 180, 210, 40));

        ADD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ADD.setText("ADD");
        ADD.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ADD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ADDMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ADDMouseEntered(evt);
            }
        });
        jPanel1.add(ADD, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 180, 140, 40));

        txtExercise.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtExercise.setForeground(new java.awt.Color(72, 84, 96));
        txtExercise.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtExercise.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 1, new java.awt.Color(0, 0, 0)));
        txtExercise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtExerciseActionPerformed(evt);
            }
        });
        jPanel1.add(txtExercise, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 100, 410, 40));

        jLabel40.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 100, 20, 40));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Instructor Name");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 160, 30));

        tableSchedule.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NUMBER", "EXERCISE NAME", "FERQUENCY"
            }
        ));
        tableSchedule.setOpaque(false);
        tableSchedule.setRowHeight(25);
        tableSchedule.setSelectionBackground(new java.awt.Color(97, 108, 112));
        jScrollPane2.setViewportView(tableSchedule);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 290, 500, 190));

        cmbMid.setAutoscrolls(true);
        cmbMid.setColorArrow(new java.awt.Color(170, 166, 157));
        cmbMid.setColorBorde(new java.awt.Color(170, 166, 157));
        cmbMid.setColorFondo(new java.awt.Color(170, 166, 157));
        cmbMid.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        cmbMid.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbMidItemStateChanged(evt);
            }
        });
        jPanel1.add(cmbMid, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 270, 40));

        cmbInstructorId.setColorArrow(new java.awt.Color(170, 166, 157));
        cmbInstructorId.setColorBorde(new java.awt.Color(170, 166, 157));
        cmbInstructorId.setColorFondo(new java.awt.Color(79, 87, 99));
        cmbInstructorId.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        cmbInstructorId.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbInstructorIdItemStateChanged(evt);
            }
        });
        jPanel1.add(cmbInstructorId, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 270, 40));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Member Name");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 150, 30));

        jLabel41.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 20, 40));

        labInstructorName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labInstructorName.setForeground(new java.awt.Color(72, 84, 96));
        labInstructorName.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        labInstructorName.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 1, new java.awt.Color(0, 0, 0)));
        labInstructorName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                labInstructorNameActionPerformed(evt);
            }
        });
        jPanel1.add(labInstructorName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 600, 40));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText(" REMOVE");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 240, 140, 40));

        tableScheduleDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "SCHEDULE ID", "INSTRUCTOR ID", "INSTROCTOR NAME", "MEMBER ID", "MEMBER NAME", "DATE"
            }
        ));
        tableScheduleDetails.setOpaque(false);
        tableScheduleDetails.setRowHeight(25);
        tableScheduleDetails.setSelectionBackground(new java.awt.Color(97, 108, 112));
        tableScheduleDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableScheduleDetailsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableScheduleDetails);
        if (tableScheduleDetails.getColumnModel().getColumnCount() > 0) {
            tableScheduleDetails.getColumnModel().getColumn(0).setResizable(false);
            tableScheduleDetails.getColumnModel().getColumn(0).setHeaderValue("SCHEDULE ID");
            tableScheduleDetails.getColumnModel().getColumn(1).setHeaderValue("INSTRUCTOR ID");
            tableScheduleDetails.getColumnModel().getColumn(2).setHeaderValue("INSTROCTOR NAME");
            tableScheduleDetails.getColumnModel().getColumn(3).setHeaderValue("MEMBER ID");
            tableScheduleDetails.getColumnModel().getColumn(4).setHeaderValue("MEMBER NAME");
            tableScheduleDetails.getColumnModel().getColumn(5).setHeaderValue("DATE");
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 1350, 200));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(11, 227, 126));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("SAVE ");
        jLabel3.setToolTipText("");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(11, 227, 126), 2));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 710, 120, 50));

        txtNo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 100, 50, 40));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Print");
        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 240, 110, 40));

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/gym/pos/Image/search_40px.png"))); // NOI18N
        jLabel22.setOpaque(true);
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, 50, 40));

        jLabel23.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 440, 10, 40));

        searchbar.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        searchbar.setForeground(new java.awt.Color(72, 84, 96));
        searchbar.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        searchbar.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        searchbar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchbarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searchbarMouseExited(evt);
            }
        });
        searchbar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbarActionPerformed(evt);
            }
        });
        searchbar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchbarKeyReleased(evt);
            }
        });
        jPanel1.add(searchbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, 430, 40));

        DELETE.setBackground(new java.awt.Color(255, 255, 255));
        DELETE.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        DELETE.setForeground(new java.awt.Color(255, 77, 77));
        DELETE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DELETE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/gym/pos/Image/button.png"))); // NOI18N
        DELETE.setText("DELETE");
        DELETE.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 77, 77), 2));
        DELETE.setOpaque(true);
        DELETE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DELETEMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DELETEMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DELETEMouseExited(evt);
            }
        });
        jPanel1.add(DELETE, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 710, 140, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1370, 770));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void labCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labCloseMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_labCloseMouseClicked

    private void labCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labCloseMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_labCloseMouseEntered

    private void labCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labCloseMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_labCloseMouseExited

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        // TODO add your handling code here:
        this.setExtendedState(ScheduleDetailsForm.ICONIFIED);
    }//GEN-LAST:event_jLabel18MouseClicked

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        // TODO add your handling code here:
        DashBord dash = new DashBord();
        dash.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel19MouseClicked

    private void labIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_labIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_labIdActionPerformed

    private void labMemberNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_labMemberNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_labMemberNameActionPerformed

    private void labFequencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_labFequencyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_labFequencyActionPerformed

    private void txtExerciseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtExerciseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtExerciseActionPerformed

    private void ADDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADDMouseClicked
        // TODO add your handling code here:
        exerciseId();
        String no=txtNo.getText();
        String exercise=txtExercise.getText();
        String Fequency=labFequency.getText();
        if(no.isEmpty() || exercise.isEmpty() || Fequency.isEmpty()){
            JOptionPane.showMessageDialog(this,"Please fill exercises details and \ntry again..");
            
            
        }else{
        DefaultTableModel model = (DefaultTableModel) tableSchedule.getModel();
        model.addRow(new Object[]{
            no, exercise, Fequency
                
        });
        clearExercise();
       
        }


    }//GEN-LAST:event_ADDMouseClicked

    private void cmbMidItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbMidItemStateChanged

        try {
            // TODO add your handling code here:
            if(cmbMid.getSelectedIndex() != -1){
            String memberId = cmbMid.getSelectedItem().toString();
            MemberModel m = new MemberController().getMemberName(memberId);
            labMemberName.setText(m.getName());
            }else{
                labMemberName.setText(null);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ScheduleDetailsForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_cmbMidItemStateChanged

    private void labInstructorNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_labInstructorNameActionPerformed


    }//GEN-LAST:event_labInstructorNameActionPerformed

    private void cmbInstructorIdItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbInstructorIdItemStateChanged
        try {
            // TODO add your handling code here:
            if(cmbInstructorId.getSelectedIndex()!= -1){
            String InstroctorId = cmbInstructorId.getSelectedItem().toString();
            InstructorModel m = new InstructorController().searchInstructor(InstroctorId);
            labInstructorName.setText(m.getName());
           }else{
             labInstructorName.setText(null);  
           }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ScheduleDetailsForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmbInstructorIdItemStateChanged

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:

        int selectedRow = tableSchedule.getSelectedRow();
        if(selectedRow == -1){
            JOptionPane.showMessageDialog(this,"Please select exercise and \ntry again...");
            //return ;
        }
        DefaultTableModel model = (DefaultTableModel) tableSchedule.getModel();
        model.removeRow(selectedRow);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void labFequencyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_labFequencyKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_labFequencyKeyReleased

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked


        try {
            ArrayList<ScheduleDetailsModel> scheuledDetailList = new ArrayList<>();
            DefaultTableModel dtm = (DefaultTableModel) tableSchedule.getModel();
            String schedule_id = labId.getText();
            for (int i = 0; i < dtm.getRowCount(); i++) {
                String No = dtm.getValueAt(i, 0).toString();
                String Exercise = dtm.getValueAt(i, 1).toString();
                String Ferquency = dtm.getValueAt(i, 2).toString();
                ScheduleDetailsModel sd = new ScheduleDetailsModel(schedule_id, No, Exercise, Ferquency);
                scheuledDetailList.add(sd);
            }
            
          
           String Sid= labId.getText();
           String Mid= cmbMid.getSelectedItem().toString();
           String mName= labMemberName.getText();
           String Iid=cmbInstructorId.getSelectedItem().toString();
           String iName=labInstructorName.getText();
           String date=labDate.getText();
           ArrayList<ScheduleDetailsModel> sdm=scheuledDetailList;
           
          
            ScheduleModel   s = new ScheduleModel(Sid,Mid,mName,Iid,iName,date, sdm);
          //labId.getText(), cmbMid.getSelectedItem().toString(), labMemberName.getText(), cmbInstructorId.getSelectedItem().toString(), labInstructorName.getText(), labDate.getText(), scheuledDetailList);
            boolean b=new ScheduleController().addSchedule(s);
            
            
            if (b) {
                JOptionPane.showMessageDialog(this, "Save ...");
                generateScheduleId();
                dtm.setRowCount(0);
                detailsRefrish();
                
                clear();
                
                
            } else {
                JOptionPane.showMessageDialog(this, "try again !!!");
            }
           
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ScheduleDetailsForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jLabel3MouseClicked
       private int selectedRow;
       private DefaultTableModel dft;
    private void tableScheduleDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableScheduleDetailsMouseClicked
       
        try {
             model=(DefaultTableModel) tableScheduleDetails.getModel();
            selectedRow=tableScheduleDetails.getSelectedRow();
            String id=  model.getValueAt(selectedRow, 0).toString();
            //---------------------------------------------------------------------
            
            dft=(DefaultTableModel) tableSchedule.getModel();
            dft.setRowCount(0);
            
            //--------------------------------------------------------------------
            ArrayList<ScheduleDetailsModel> scheduleDetails = ScheduleController.getScheduleDetails(id);
            //model.setRowCount(0);
            for (ScheduleDetailsModel sd : scheduleDetails) {
                Object[] rowData={sd.getNo(),sd.getExercise(),sd.getFerquency()};
                dft.addRow(rowData);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ScheduleDetailsForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_tableScheduleDetailsMouseClicked

    private void searchbarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchbarMouseEntered
        // TODO add your handling code here:
        searchbar.setText(null);
    }//GEN-LAST:event_searchbarMouseEntered

    private void searchbarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchbarMouseExited
        // TODO add your handling code here:
        searchbar.setText("Search...");
    }//GEN-LAST:event_searchbarMouseExited

    private void searchbarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchbarActionPerformed

    private void searchbarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchbarKeyReleased
        try {
            // TODO add your handling code here:
            model.setRowCount(0);
            List<ScheduleModel> allSchedule = new ScheduleController().searchAllSchedule(searchbar.getText());
            for(ScheduleModel temp: allSchedule){
                model.addRow(new Object[]{
                    temp.getSchedule_id(),
                    temp.getInstructor_id(),
                    temp.getInstructor_name(),
                    temp.getMember_id(),
                    temp.getMember_name(),
                    temp.getDate(),
                    
                    
                    
                });
                
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ScheduleDetailsForm.class.getName()).log(Level.SEVERE, null, ex);
        }
           

    }//GEN-LAST:event_searchbarKeyReleased

    private void ADDMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADDMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_ADDMouseEntered

    private void DELETEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DELETEMouseClicked
       
        try {
            // TODO add your handling code here:
            selectedRow=tableScheduleDetails.getSelectedRow();
            String id=  model.getValueAt(selectedRow, 0).toString();
            
            if(new ScheduleController().deleteSchedule(id)){
                JOptionPane.showMessageDialog(this,"delete");
                detailsRefrish();
                dft.setRowCount(0);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ScheduleDetailsForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_DELETEMouseClicked

    private void DELETEMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DELETEMouseEntered
        // TODO add your handling code here:
       DELETE.setForeground(new java.awt.Color(255, 255, 255));
       DELETE.setBackground(new java.awt.Color(255, 77, 77));
    }//GEN-LAST:event_DELETEMouseEntered

    private void DELETEMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DELETEMouseExited
        // TODO add your handling code here:
        DELETE.setForeground(new java.awt.Color(255, 77, 77));
        DELETE.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_DELETEMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScheduleDetailsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScheduleDetailsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScheduleDetailsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScheduleDetailsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScheduleDetailsForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ADD;
    private javax.swing.JLabel DELETE;
    private rojerusan.RSComboMetro cmbInstructorId;
    private rojerusan.RSComboMetro cmbMid;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labClose;
    private javax.swing.JLabel labDate;
    private javax.swing.JTextField labFequency;
    private javax.swing.JTextField labId;
    private javax.swing.JTextField labInstructorName;
    private javax.swing.JTextField labMemberName;
    private javax.swing.JTextField searchbar;
    private javax.swing.JTable tableSchedule;
    private javax.swing.JTable tableScheduleDetails;
    private javax.swing.JTextField txtExercise;
    private javax.swing.JTextField txtNo;
    // End of variables declaration//GEN-END:variables

    

    private void loadAllMemberId() {
        try {
            ArrayList<MemberModel> Member = new MemberController().allMemberId();

            for (MemberModel Mem : Member) {
                cmbMid.addItem(Mem.getmId());

            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ScheduleDetailsForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loadAllInstroctorId() {

        try {
            ArrayList<InstructorModel> Instructor = new InstructorController().getAllInstructor();

            for (InstructorModel Ins : Instructor) {
                cmbInstructorId.addItem(Ins.getId());

            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ScheduleDetailsForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    //date of join----formatDate
    private String formatDate(Date date) {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        return sdf.format(date);

    }

    private void generateScheduleId() {

        try {
            String instructorId = new ScheduleController().generateId();

            labId.setText(instructorId);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ScheduleDetailsForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

   DefaultTableModel model;
    private void detailsRefrish() {
       
     
        try {
            ArrayList<ScheduleModel> allSchedule = ScheduleController.getAllSchedule();
         
            model=(DefaultTableModel) tableScheduleDetails.getModel();
            model.setRowCount(0);
           
            for (ScheduleModel schedule : allSchedule) {
             
                Object[] rowData={schedule.getSchedule_id(),schedule.getInstructor_id(),schedule.getInstructor_name(),schedule.getMember_id(),schedule.getMember_name(),schedule.getDate()};
                
                model.addRow(rowData);
                
               
            }   
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ScheduleDetailsForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    
    private void clear(){
        //cmbMid.setSelectedItem(null);
        cmbMid.setSelectedIndex(-1);
        //labMemberName.setText(null);
        cmbInstructorId.setSelectedIndex(-1);
        //labInstructorName.setText(null);
        txtExercise.setText(null);
        labFequency.setText(null);
        
    }
    
    private void clearExercise(){
        txtExercise.setText(null);
        labFequency.setText(null);
        txtNo.setText(null);
    }

    private void exerciseId() {
        
        int i=Integer.parseInt(txtNo.getText());
        if(true){
            i++;
            txtNo.setText(i+"");
         }
        
      }

   
    private void tableCustamization(){
       tableScheduleDetails.getTableHeader().setFont(new Font("Segoe UI",Font.BOLD,15));
       tableScheduleDetails.getTableHeader().setOpaque(false);
       tableScheduleDetails.getTableHeader().setBackground(new Color(255, 255, 255));
       tableScheduleDetails.getTableHeader().setForeground(new Color(30, 39, 46));
       
       
       
       
       tableSchedule.getTableHeader().setFont(new Font("Segoe UI",Font.BOLD,15));
       tableSchedule.getTableHeader().setOpaque(false);
       tableSchedule.getTableHeader().setBackground(new Color(255, 255, 255));
       tableSchedule.getTableHeader().setForeground(new Color(30, 39, 46));
       
    }
    
    
    
    
}
